// Generated by Ember Setup v0.6.0 (framework v0.12.0) — 框架演示代码（全文件框架所有）

using Ember.Core;
using Ember.Table;
using Ember.Table.Integration;

using Game.Table.Generated;

namespace Game.Module
{
    /// <summary>项目级 Resource → Table Engine 薄接线；默认关闭，按产品需要启用。</summary>
    [EmberModule(ModulePhase.Global, Enabled = false)]
    public sealed partial class GameTableModule : EmberTableModuleBase<GameTableModule>
    {
        protected override IEmberTableCatalog CreateTableCatalog()
        {
            return GameTables.CreateCatalog();
        }

        protected override void OnTableModuleInitialized()
        {
            OnGameTableModuleInitialized();
        }

        protected override void OnTableModuleDestroying()
        {
            OnGameTableModuleDestroying();
        }

        protected override void ResetTableModuleData()
        {
            OnResetGameTableModuleData();
        }

        partial void OnGameTableModuleInitialized();
        partial void OnGameTableModuleDestroying();
        partial void OnResetGameTableModuleData();
    }
}
