// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 框架主菜单页面逻辑（生成区文件，框架所有）
/*=============================================================
 * author       : DESKTOP-5SRUU55
 * prefab name  : EUIMainPanel
 * page name    : EUIMainPage
 * 本文件为框架生成（混合文件）：
 *   [EmberManaged] 块内 = 框架所有（生命周期 override，刷新时整块替换，勿改）；
 *   块外 = 用户级生命周期（XxxUser 方法），用户只改这里，永不触碰
 ==============================================================*/
using Ember.Basic;
using Ember.Core;
using Ember.UI;

namespace Game.UI
{
    public partial class EUIMainPage
    {
        // ── 框架生命周期（块内框架所有；每个 override 末尾调用对应的用户级钩子）──
        // [EmberManaged:begin Lifecycle]
        private const string TAG = LogTags.Game + "." + nameof(EUIMainPage);

        public override void OnInit()
        {
            base.OnInit();

            Btn_Start.onClick.AddListener(() =>
                GameLauncher.Instance.Fsm.TransitionTo<GameplayState>());

            Btn_Settings.onClick.AddListener(() =>
                GameLauncher.Instance.Fsm.TransitionTo<SettingsState>(SettingsContext.Main));

            OnInitUser();
        }

        public override void OnOpen(object param)
        {
            base.OnOpen(param);
            OnOpenUser(param);
        }

        public override void OnShow()
        {
            base.OnShow();
            OnShowUser();
        }

        public override void OnPause()
        {
            base.OnPause();
            EmberDebug.Log(TAG, "EUIMainPage 被遮挡");
        }

        public override void OnResume()
        {
            base.OnResume();
            EmberDebug.Log(TAG, "EUIMainPage 恢复可见");
        }

        public override void OnHide()
        {
            base.OnHide();
            OnHideUser();
        }

        public override void OnClose()
        {
            base.OnClose();
            OnCloseUser();
        }

        public override void OnDispose()
        {
            Btn_Start.onClick.RemoveAllListeners();
            Btn_Settings.onClick.RemoveAllListeners();
            base.OnDispose();
            OnDisposeUser();
        }
        // [EmberManaged:end]

        // ── 用户级生命周期（块外用户区，永不触碰）──

        /// <summary>用户初始化钩子：框架 OnInit 结束时调用。</summary>
        private void OnInitUser()
        {
            Btn_Start.onClick.RemoveAllListeners();
            Btn_Start.onClick.AddListener(() =>
            {
                if (NovelSaveUI.IsLoading || NovelSaveUI.Module?.IsBusy == true) return;
                NovelSaveUI.StartNewGame();
            });
            NovelContinue.onClick.AddListener(NovelSaveUI.Continue); NovelLoad.onClick.AddListener(NovelSaveUI.Open);
            NovelQuit.onClick.AddListener(QuitGame);
            // 主界面图片同样按当前小说套皮肤；与阅读页共用同一套解析（NarrativeLibrarySO.Current）。
            Game.Narrative.NovelSkin.Apply(this, "EUIMainPanel");
        }
        private void QuitGame()
        {
            if (NovelSaveUI.IsLoading || _novelSave?.IsBusy == true) return;
            GameLauncher.Instance.Quit();
        }
        private Game.NovelSave.NovelSaveModule _novelSave;
        private void RefreshNovelSave()
        {
            NovelMessage.text = _novelSave?.Message ?? "";
            bool busy = NovelSaveUI.IsLoading || _novelSave?.IsBusy == true;
            bool hasAny = false, hasManual = false;
            if (_novelSave != null)
                foreach (var slot in _novelSave.Store.Slots)
                { hasAny = true; if (slot.Slot >= 0 && slot.Slot < 6) hasManual = true; }
            NovelContinue.gameObject.SetActive(hasAny);
            NovelLoad.gameObject.SetActive(hasManual);
            Btn_Start.interactable = !busy; Btn_Settings.interactable = !busy; NovelQuit.interactable = !busy;
            NovelContinue.interactable = _novelSave != null && !busy && _novelSave.Store.Latest >= 0;
            NovelLoad.interactable = _novelSave != null && !busy;
        }

        /// <summary>用户打开钩子：框架 OnOpen 结束时调用。</summary>
        private void OnOpenUser(object param)
        {
            var library = UnityEngine.Resources.Load<Game.Narrative.NarrativeLibrarySO>(Game.Narrative.NarrativeLibrarySO.RESOURCE_PATH);
            NovelTitle.text = library && library.Current ? library.Current.LocalizedDisplayName : "视觉小说";
            _novelSave = NovelSaveUI.Module;
            if (_novelSave != null) _novelSave.Changed += RefreshNovelSave;
            RefreshNovelSave();
        }

        /// <summary>用户显示钩子：框架 OnShow 结束时调用。</summary>
        private void OnShowUser()
        {
            RefreshNovelSave();
        }

        /// <summary>用户隐藏钩子：框架 OnHide 结束时调用。</summary>
        private void OnHideUser()
        {
            // 页面被隐藏
        }

        /// <summary>用户关闭钩子：框架 OnClose 结束时调用。</summary>
        private void OnCloseUser()
        {
            if (_novelSave != null) _novelSave.Changed -= RefreshNovelSave; _novelSave = null;
        }

        /// <summary>用户释放钩子：框架 OnDispose 结束时调用。</summary>
        private void OnDisposeUser()
        {
            OnCloseUser(); NovelContinue.onClick.RemoveListener(NovelSaveUI.Continue); NovelLoad.onClick.RemoveListener(NovelSaveUI.Open);
            NovelQuit.onClick.RemoveListener(QuitGame);
        }
    }
}
