// Copyright (c) 2026 Ember Unity Framework. All rights reserved.
// Package: com.ember.core

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Ember.Basic;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEditor.PackageManager;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Ember.Core.Editor
{
    /// <summary>
    /// Ember 项目脚手架向导 —— 从包内 Templates~ 模板生成业务骨架 + 最小可运行启动场景。
    ///
    /// 目标体验（见 docs/dev/upm-migration-plan.md §6.1）：
    /// 导包 → Ember/Setup/初始化项目 → 打开 FrameworkScene → Play 跑通 Init→Main。
    ///
    /// 幂等：已存在的文件跳过；重复运行只补缺失项，不覆盖用户代码。
    /// </summary>
    public static class EmberProjectSetup
    {
        #region 内部参数

        private const string TAG = LogTags.CoreEditor;
        private const string CORE_PACKAGE = "com.ember.core";
        private const string UI_PACKAGE = "com.ember.ui";
        private const string MarkerPrefix = "Generated by Ember Setup v";

        private const string StateDir = "Assets/Game/State";
        private const string UIDir = "Assets/Game/UI";
        private const string ScenesDir = "Assets/Game/Scenes";
        private const string FrameworkScenePath = ScenesDir + "/FrameworkScene.unity";
        private const string MainScenePath = ScenesDir + "/MainScene.unity";

        /// <summary>生成清单：(包内模板相对路径, 目标路径, 命名空间)</summary>
        private static readonly (string tpl, string dest, string ns)[] CoreTemplates =
        {
            ("State/GameInitState.cs.tpl",      StateDir + "/GameInitState.cs",      "Game.State"),
            ("State/GameMainState.cs.tpl",      StateDir + "/GameMainState.cs",      "Game.State"),
            ("State/GameGameplayState.cs.tpl",  StateDir + "/GameGameplayState.cs",  "Game.State"),
            ("State/GameSettingsState.cs.tpl",  StateDir + "/GameSettingsState.cs",  "Game.State"),
            ("UI/EUIMainAnimationStarter.cs.tpl",  UIDir + "/EUIMainAnimationStarter.cs",  "Game.UI"),
            ("UI/EUIDefaultMainAnimation.cs.tpl",  UIDir + "/EUIDefaultMainAnimation.cs",  "Game.UI"),
        };

        #endregion

        // --------------------------------------------------------

        #region 外部方法

        [MenuItem("Ember/Setup/初始化项目", false, 100)]
        public static void SetupProject()
        {
            var created = new List<string>();

            // 1. 目录结构
            EnsureFolder(StateDir);
            EnsureFolder(UIDir);
            EnsureFolder(ScenesDir);

            // 2. 从 com.ember.core 模板生成状态类与开屏动画
            var corePath = GetResolvedPath(CORE_PACKAGE);
            if (corePath == null)
            {
                EditorUtility.DisplayDialog("初始化失败", $"未找到包 {CORE_PACKAGE}，请确认已安装。", "确定");
                return;
            }

            var coreTplDir = Path.Combine(corePath, "Editor", "Templates~");
            var version = ReadPackageVersion(corePath);

            foreach (var (tpl, dest, ns) in CoreTemplates)
            {
                if (RenderTemplate(Path.Combine(coreTplDir, tpl), dest, ns, version))
                    created.Add(dest);
            }

            // 3. GamePages.cs（来自 com.ember.ui 的模板）
            var uiPath = GetResolvedPath(UI_PACKAGE);
            if (uiPath != null)
            {
                var gamePagesTpl = Path.Combine(uiPath, "Editor", "Templates~", "GamePages.cs.tpl");
                if (RenderTemplate(gamePagesTpl, UIDir + "/GamePages.cs", "Game.UI", version))
                    created.Add(UIDir + "/GamePages.cs");
            }
            else
            {
                EmberDebug.LogWarning(TAG, $"{UI_PACKAGE} 未安装，跳过 GamePages.cs 生成。");
            }

            // 4. 最小可运行场景（FrameworkScene 立即创建；MainScene 动画组件待编译完成后挂载）
            CreateFrameworkScene();
            CreateMainSceneShell();
            RegisterBuildSettings();

            // 5. 编译完成后给 MainScene 挂 EUIDefaultMainAnimation（刚生成的脚本需先编译，挂载幂等）
            CompilationPipeline.compilationFinished -= OnCompilationFinished;
            CompilationPipeline.compilationFinished += OnCompilationFinished;

            AssetDatabase.Refresh();

            // 6. 打开启动场景，用户可直接点 Play
            if (File.Exists(FrameworkScenePath))
                EditorSceneManager.OpenScene(FrameworkScenePath);

            var msg = created.Count > 0
                ? $"初始化完成：生成 {created.Count} 个文件（幂等跳过已存在项）。\n\n已打开 {FrameworkScenePath}，可直接点 Play。"
                : "初始化完成：生成区文件均已存在，无需重复生成。";
            EditorUtility.DisplayDialog("Ember 项目初始化", msg, "确定");
            EmberDebug.LogInit(TAG, $"EmberProjectSetup 完成：新增 {created.Count} 个文件。");
        }

        [MenuItem("Ember/Setup/校验生成物一致性", false, 101)]
        public static void ValidateGeneratedFiles()
        {
            var corePath = GetResolvedPath(CORE_PACKAGE);
            if (corePath == null) return;
            var version = ReadPackageVersion(corePath);

            var report = new List<string>();
            foreach (var (_, dest, _) in CoreTemplates)
            {
                var marker = ReadMarkerVersion(dest);
                var status = marker == null
                    ? "⚠️ 缺失（可重跑初始化补全）"
                    : marker == version
                        ? "✅ 一致"
                        : $"🔶 模板版本 {marker} ≠ 当前框架 {version}（骨架升级可用，业务代码不受影响）";
                report.Add($"{dest}\n    {status}");
            }
            report.Add($"{FrameworkScenePath}\n    {(File.Exists(FrameworkScenePath) ? "✅ 存在" : "⚠️ 缺失")}");
            report.Add($"{MainScenePath}\n    {(File.Exists(MainScenePath) ? "✅ 存在" : "⚠️ 缺失")}");

            EditorUtility.DisplayDialog("生成物一致性校验", string.Join("\n", report), "确定");
        }

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        private static string GetResolvedPath(string packageName)
        {
            var info = UnityEditor.PackageManager.PackageInfo.FindForPackageName(packageName);
            return info?.resolvedPath;
        }

        private static string ReadPackageVersion(string resolvedPath)
        {
            var jsonPath = Path.Combine(resolvedPath, "package.json");
            if (!File.Exists(jsonPath)) return "0.0.0";
            var match = System.Text.RegularExpressions.Regex.Match(
                File.ReadAllText(jsonPath), @"""version""\s*:\s*""(\d+\.\d+\.\d+)""");
            return match.Success ? match.Groups[1].Value : "0.0.0";
        }

        private static void EnsureFolder(string assetPath)
        {
            var parts = assetPath.Split('/');
            var current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                var parent = current;
                current += "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(current))
                    AssetDatabase.CreateFolder(parent, parts[i]);
            }
        }

        /// <summary>渲染模板到目标路径；已存在则跳过（幂等，不覆盖用户代码）。</summary>
        private static bool RenderTemplate(string tplPath, string destPath, string namespaceName, string version)
        {
            if (!File.Exists(tplPath))
            {
                EmberDebug.LogWarning(TAG, $"模板缺失：{tplPath}");
                return false;
            }
            if (File.Exists(destPath))
                return false;

            var content = File.ReadAllText(tplPath)
                .Replace("{NAMESPACE}", namespaceName)
                .Replace("{EMBED_VERSION}", version);

            var dir = Path.GetDirectoryName(destPath);
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(destPath, content, new System.Text.UTF8Encoding(false));
            AssetDatabase.ImportAsset(destPath);
            EmberDebug.LogInit(TAG, $"生成：{destPath}（{namespaceName}，v{version}）");
            return true;
        }

        private static void CreateFrameworkScene()
        {
            if (File.Exists(FrameworkScenePath)) return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;

            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // GameBoot —— 框架入口
            var boot = new GameObject("GameBoot");
            boot.AddComponent<GameLauncher>();

            // 主相机
            var camGo = new GameObject("Main Camera");
            camGo.tag = "MainCamera";
            camGo.AddComponent<Camera>();
            camGo.AddComponent<AudioListener>();

            // 事件系统（按可用程序集降级：InputSystemUIInputModule → StandaloneInputModule）
            var eventSystemType = Type.GetType("UnityEngine.EventSystems.EventSystem, UnityEngine.UI");
            if (eventSystemType != null)
            {
                var es = new GameObject("EventSystem");
                es.AddComponent(eventSystemType);
                var inputModuleType = Type.GetType("UnityEngine.InputSystem.UI.InputSystemUIInputModule, Unity.InputSystem");
                if (inputModuleType == null)
                    inputModuleType = Type.GetType("UnityEngine.EventSystems.StandaloneInputModule, UnityEngine.UI");
                if (inputModuleType != null)
                    es.AddComponent(inputModuleType);
            }

            // UIRoot —— 视图引擎运行时自建 Canvas 层根
            new GameObject("UIRoot");

            EditorSceneManager.SaveScene(scene, FrameworkScenePath);
            EmberDebug.LogInit(TAG, $"创建场景：{FrameworkScenePath}");
        }

        private static void CreateMainSceneShell()
        {
            if (File.Exists(MainScenePath)) return;
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            EditorSceneManager.SaveScene(scene, MainScenePath);
            EmberDebug.LogInit(TAG, $"创建场景：{MainScenePath}（动画组件编译后自动挂载）");
        }

        private static void RegisterBuildSettings()
        {
            var scenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
            if (!scenes.Any(s => s.path == FrameworkScenePath))
                scenes.Insert(0, new EditorBuildSettingsScene(FrameworkScenePath, true));
            if (!scenes.Any(s => s.path == MainScenePath))
                scenes.Insert(1, new EditorBuildSettingsScene(MainScenePath, true));
            EditorBuildSettings.scenes = scenes.ToArray();
        }

        private static void OnCompilationFinished(object obj)
        {
            CompilationPipeline.compilationFinished -= OnCompilationFinished;
            AddMainAnimationComponent();
        }

        private static void AddMainAnimationComponent()
        {
            if (!File.Exists(MainScenePath)) return;

            var type = Type.GetType("Game.UI.EUIDefaultMainAnimation, Assembly-CSharp");
            if (type == null)
            {
                EmberDebug.LogWarning(TAG, "EUIDefaultMainAnimation 类型未找到（可能不在 Assembly-CSharp），跳过 MainScene 动画组件挂载。");
                return;
            }

            EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
            var scene = EditorSceneManager.OpenScene(MainScenePath, OpenSceneMode.Additive);

            // 幂等：已挂载则跳过
            bool alreadyAdded = false;
            foreach (var root in scene.GetRootGameObjects())
            {
                if (root.GetComponentInChildren(type, true) != null) { alreadyAdded = true; break; }
            }

            if (!alreadyAdded)
            {
                var go = new GameObject("MainAnimation");
                go.AddComponent(type);
                EditorSceneManager.SaveScene(scene, MainScenePath);
                EmberDebug.LogInit(TAG, "MainScene 已挂载 EUIDefaultMainAnimation。");
            }

            EditorSceneManager.CloseScene(scene, true);
        }

        private static string ReadMarkerVersion(string filePath)
        {
            if (!File.Exists(filePath)) return null;
            foreach (var line in File.ReadAllLines(filePath))
            {
                var idx = line.IndexOf(MarkerPrefix, StringComparison.Ordinal);
                if (idx >= 0)
                {
                    var rest = line.Substring(idx + MarkerPrefix.Length).Trim();
                    var end = rest.IndexOfAny(new[] { ' ', '\t', '—', '-' });
                    return end > 0 ? rest.Substring(0, end) : rest;
                }
            }
            return null;
        }

        #endregion
    }
}
