// Generated by Ember Setup v{EMBED_VERSION} — 游戏层 Settings 状态
// 基类 SettingsState 位于 com.ember 包内；本文件由 Ember/Setup/初始化项目 从模板生成。
using Ember.Core;
using Ember.UI;

namespace {NAMESPACE}
{
    /// <summary>
    /// 游戏层 SettingsState 子类 —— 把状态机 Push/Pop 与 UI 层桥接。
    /// 覆盖式设置：从 Main 或 Gameplay Push 进入，关闭后回到原状态。
    /// </summary>
    public class GameSettingsState : SettingsState
    {
        protected override void OnSettingsEnter(object args)
        {
            // TODO: 打开设置弹窗
            // EUIManager.Instance.ShowPopup(GamePages.Settings, args);
        }

        protected override void OnSettingsExit()
        {
            // TODO: 关闭设置弹窗
            // EUIManager.Instance.CloseAllPopups();
        }
    }
}
