// Generated by Ember Setup v{EMBED_VERSION} — 游戏层 Main 状态
// 基类 MainState 位于 com.ember 包内；本文件由 Ember/Setup/初始化项目 从模板生成。
using Ember.Core;
using Ember.UI;

namespace {NAMESPACE}
{
    /// <summary>
    /// 游戏层 MainState 子类 —— override 框架钩子，注入业务逻辑。
    /// Init 完成后自动过渡到本状态（大厅/主界面枢纽）。
    /// </summary>
    public class GameMainState : MainState
    {
        protected override void OnMainEnter(object args)
        {
            base.OnMainEnter(args);

            // TODO: 进入大厅——注册默认 Loading 页、播放 BGM 等
            // EUIManager.DefaultLoadingPageDef = GamePages.EUILoadingPage;
        }

        protected override void OnMainExit()
        {
            // TODO: 离开大厅——清理背景等
            base.OnMainExit();
        }

        protected override void OnOpeningAnimationEnd()
        {
            // TODO: 开屏动画结束 → 打开主页面
            // EUIManager.Instance.ShowMainPage(GamePages.MainMenu);
        }
    }
}
