// Generated by Ember Setup v{EMBED_VERSION} — 游戏层 Init 状态
// 基类 InitState 位于 com.ember 包内；本文件由 Ember/Setup/初始化项目 从模板生成。
using Ember.Core;

namespace {NAMESPACE}
{
    /// <summary>
    /// 游戏层 InitState 子类 —— override 框架钩子，注入业务逻辑。
    /// 框架初始化（Manager + 全局模块）完成后由状态机自动进入本状态。
    /// </summary>
    public class GameInitState : InitState
    {
        public override void OnEnter(object args)
        {
            base.OnEnter(args);

            // TODO: 框架就绪后的业务逻辑（如创建常驻调试页）
        }
    }
}
