// Generated by Ember Setup — SceneUI 业务模块接入点
using System;

using Ember.Camera;
using Ember.Core;
using Ember.SceneUI;
using Ember.SceneUI.Integration;

using Game.UI;

using UnityEngine;

namespace Game.Module
{
    /// <summary>业务 SceneUI Channel 标识。一个 Channel 对应一套宿主页、相机与投影环境。</summary>
    public enum SceneUIChannelId
    {
        World = 1,
    }

    /// <summary>业务 SceneUI View 标识。每个值对应 SceneUIViewCatalog 中的一种气泡预制体。</summary>
    public enum SceneUIViewId
    {
        Example = 1001,
    }

    /// <summary>
    /// 项目 SceneUI 模块。
    /// World Channel 使用 EUISceneUIPage 作为宿主页，并由业务显式提供相机与 View Catalog。
    /// </summary>
    [EmberModule(ModulePhase.Gameplay)]
    public sealed class SceneUIModule : EmberSceneUIModuleBase<SceneUIModule>
    {
        #region 内部参数

        private const string VIEW_CATALOG_RESOURCE_PATH =
            "UI/Module/SceneUI/SceneUIViewCatalog";

        private static readonly ISceneUIBinder ExampleBubbleBinderInstance =
            new ExampleBubbleBinder();

        public static readonly SceneUIChannelKey WorldChannel =
            new SceneUIChannelKey((int)SceneUIChannelId.World);

        public static readonly SceneUIViewKey ExampleView =
            new SceneUIViewKey((int)SceneUIViewId.Example);

        private sealed class ExampleBubbleBinder : ISceneUIBinder
        {
            private const string VIEW_NAME = "EUIBaseBubbleItem";

            public void Bind(ISceneUIView view, SceneUIHandle handle)
            {
                ValidateAndNameView(view);
            }

            public void RefreshContent(ISceneUIView view)
            {
                ValidateAndNameView(view);
            }

            public void Unbind(ISceneUIView view)
            {
                if (view?.RectTransform)
                    view.RectTransform.name = VIEW_NAME;
            }

            private static void ValidateAndNameView(ISceneUIView view)
            {
                if (!(view is EUIItemSceneUIView itemView)
                    || itemView.GetLogic<EUIBaseBubbleItem>() == null)
                {
                    throw new InvalidOperationException(
                        "Example SceneUI View must be an EUIBaseBubbleItem EUI Item.");
                }

                itemView.GameObject.name = VIEW_NAME + " (SceneUI Example)";
            }
        }

        #endregion

        // --------------------------------------------------------

        #region 外部方法

        /// <summary>让一个场景 Transform 显示项目内置的 Example 气泡。</summary>
        public bool TryShowExampleBubble(
            Transform target,
            out SceneUIModuleHandle handle)
        {
            return TryShowBubble(
                target,
                SceneUIViewId.Example,
                SceneUIObjectUpdateMode.Dynamic,
                new Vector3(0f, 2f, 0f),
                true,
                out handle);
        }

        /// <summary>按业务气泡类型和物体更新方式注册一个场景 Transform。</summary>
        public bool TryShowBubble(
            Transform target,
            SceneUIViewId bubbleType,
            SceneUIObjectUpdateMode updateMode,
            Vector3 worldOffset,
            bool initiallyVisible,
            out SceneUIModuleHandle handle)
        {
            handle = default;
            if (!target
                || !TryResolveView(
                    bubbleType,
                    out SceneUIViewKey viewKey,
                    out ISceneUIBinder binder))
                return false;

            SceneUIVisibilityPolicy visibility = SceneUIVisibilityPolicy.DefaultHide;
            visibility.OutOfBoundsMode = SceneUIOutOfBoundsMode.Clamp;
            visibility.ScreenPadding = 24f;
            visibility.BoundsMode = SceneUIBoundsMode.FullRect;

            return TryRegisterSceneUI(
                WorldChannel,
                new SceneUIModuleRequest
                {
                    ViewKey = viewKey,
                    Anchor = new TransformSceneUIAnchor(target),
                    Binder = binder,
                    WorldOffset = worldOffset,
                    UiOffset = Vector2.zero,
                    UpdatePolicy = updateMode == SceneUIObjectUpdateMode.Dynamic
                        ? SceneUIUpdatePolicy.PollPosition
                        : SceneUIUpdatePolicy.Manual,
                    VisibilityPolicy = visibility,
                    ScalePolicy = SceneUIScalePolicy.Fixed,
                    ViewLifetimePolicy = SceneUIViewLifetimePolicy.RecycleAfterDelay,
                    RecycleDelaySeconds = 0.25f,
                    SortingPriority = 0,
                    ViewMetrics = default,
                    OcclusionPolicy = SceneUIOcclusionPolicy.Disabled,
                    BusinessVisible = initiallyVisible,
                },
                out handle);
        }

        /// <summary>
        /// 非 Cinemachine 相机驱动可在相机最终姿态确定后调用；当前 World Channel 已由
        /// Cinemachine CameraUpdatedEvent 自动完成同一通知。
        /// </summary>
        public bool NotifyWorldCameraUpdated()
        {
            return NotifyCameraUpdated(WorldChannel);
        }

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        protected override void RegisterSceneUIChannels()
        {
            HostedSceneUIContextOptions options = HostedSceneUIContextOptions.Default;
            options.SortingMode = SceneUISortingMode.PriorityThenDepth;
            options.PrewarmInstancesPerFlush = 4;

            RegisterCinemachineChannel(
                WorldChannel,
                GamePages.EUISceneUIPage,
                ResolveSceneCamera(),
                ResolveViewCatalog(),
                options);
        }

        protected override void OnSceneUIModuleInitialized()
        {
            ChannelReady += OnSceneUIChannelReady;
            SceneUIObject.AttachModule(this);
            base.OnSceneUIModuleInitialized();
        }

        protected override void OnSceneUIModuleDestroying()
        {
            SceneUIObject.DetachModule(this);
            ChannelReady -= OnSceneUIChannelReady;
            base.OnSceneUIModuleDestroying();
        }

        private static bool TryResolveView(
            SceneUIViewId bubbleType,
            out SceneUIViewKey viewKey,
            out ISceneUIBinder binder)
        {
            switch (bubbleType)
            {
                case SceneUIViewId.Example:
                    viewKey = ExampleView;
                    binder = ExampleBubbleBinderInstance;
                    return true;
                default:
                    viewKey = default;
                    binder = null;
                    return false;
            }
        }

        private static void OnSceneUIChannelReady(SceneUIChannelKey channelKey)
        {
            SceneUIObject.NotifyChannelReady(channelKey);
        }

        /// <summary>
        /// 主相机由 FrameworkScene.GameLauncher 显式注入 EmberCameraManager；
        /// 这里不使用 Camera.main 或场景搜索。
        /// </summary>
        private static UnityEngine.Camera ResolveSceneCamera()
        {
            return EmberCameraManager.IsValid
                ? EmberCameraManager.Instance.MainCamera
                : null;
        }

        /// <summary>通过固定 Resources 地址取得项目持有的 SceneUI View Catalog。</summary>
        private static SceneUIViewCatalog ResolveViewCatalog()
        {
            return Resources.Load<SceneUIViewCatalog>(VIEW_CATALOG_RESOURCE_PATH);
        }

        #endregion
    }
}
