// Generated by Ember Setup v{EMBED_VERSION} — 游戏层 Gameplay 状态
// 基类 GameplayState 位于 com.ember.core 包内；本文件由 Ember/Setup/初始化项目 从模板生成。
using Ember.Core;
using Ember.UI;

namespace {NAMESPACE}
{
    /// <summary>
    /// 游戏层 GameplayState 子类 —— override 框架钩子，注入业务逻辑。
    /// 从 Main 进入核心玩法时由状态机切换进入。
    /// </summary>
    public class GameGameplayState : GameplayState
    {
        protected override void OnGameplayEnter(object args)
        {
            base.OnGameplayEnter(args);

            // TODO: 进入玩法——打开游戏内 UI 等
            // EUIManager.Instance.ShowMainPage(GamePages.InGameUI);
        }

        protected override void OnGameplayExit()
        {
            // TODO: 退出玩法——清理 UI、卸载资源等
            base.OnGameplayExit();
        }
    }
}
