// Generated by Ember Setup v0.3.0 (framework v0.9.0) — Main 开屏动画基类（生成区文件）
using Cysharp.Threading.Tasks;
using Ember.Core;
using UnityEngine;

namespace Game.UI
{
    /// <summary>
    /// Main 开屏动画基类（抽象） —— 挂在 MainScene 的任意 GameObject 上。
    ///
    /// 收到 <see cref="EmberBroadcastEvent.MainSceneReady"/> 后调用
    /// <see cref="PlayOpeningAnimation"/> 播放动画（子类实现），完成后广播
    /// <see cref="EmberBroadcastEvent.OpeningAnimationEnd"/>，MainState 收到后调用
    /// <see cref="Ember.Core.MainState.OnOpeningAnimationEnd()"/>。
    ///
    /// 兜底背景页（UIBg）由 InitState 在 BootSplash 渐出前加载，与本类无关。
    ///
    /// <b>不要直接使用本类</b>，使用子类 <see cref="EUIDefaultMainAnimation"/>（无动画，立即完成）
    /// 或自定义子类 override <see cref="PlayOpeningAnimation"/>。
    /// </summary>
    public abstract class EUIMainAnimationStarter : MonoBehaviour
    {
        private void Awake()
        {
            EmberEventBus.Subscribe(EmberBroadcastEvent.MainSceneReady, OnMainSceneReady);
        }

        private void OnDestroy()
        {
            EmberEventBus.Unsubscribe(EmberBroadcastEvent.MainSceneReady, OnMainSceneReady);
        }

        private async void OnMainSceneReady()
        {
            // 开屏动画（子类实现）。背景页已在 BootSplash 渐出前由 InitState 加载完成。
            await PlayOpeningAnimation();

            EmberEventBus.OnNext(EmberBroadcastEvent.OpeningAnimationEnd);
        }

        /// <summary>
        /// 播放开屏动画。子类实现此方法，动画结束后返回（框架 await 后广播 OpeningAnimationEnd）。
        /// </summary>
        protected abstract UniTask PlayOpeningAnimation();
    }
}
