// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 游戏层 Gameplay 状态（生成区文件，含业务增量）
using Ember.Core;
using Ember.UI;
using Game.UI;
using Game.Narrative;
using Game.Module;

namespace Game.State
{
    /// <summary>
    /// 游戏层 GameplayState 子类 —— override 框架钩子，注入业务逻辑。
    ///
    /// <b>进入玩法 → 打开游戏内 UI：</b>
    /// <see cref="OnGameplayEnter"/> 在场景加载完成后调用，打开 InGameUI。
    ///
    /// <b>退出玩法 → 关闭所有 UI：</b>
    /// <see cref="OnGameplayExit"/> 在离开玩法前调用，清理 UI。
    /// </summary>
    public class GameGameplayState : GameplayState
    {
        private NarrativeModule _narrative;
        private long _entryVersion;
        // [EmberManaged:begin OnGameplayEnter]
        protected override void OnGameplayEnter(object args)
        // [EmberManaged:end]
        {
            base.OnGameplayEnter(args);
            long entry = ++_entryVersion;
            if (!EmberModuleCollector.Instance.TryGetModule(out _narrative))
                throw new System.InvalidOperationException("NarrativeModule 未装配");
            if (args is NovelPreparedGameRequest prepared) _narrative.BeginPrepared(prepared.Session);
            else _narrative.Begin(args as NovelNewGameRequest ?? new NovelNewGameRequest(), NovelSaveUI.Catalog);
            _narrative.PreparingEntryUnderCover = NovelSaveUI.IsStarting;
            _narrative.MenuRequested += ReturnToMenu;
            _narrative.FatalRestoreError += ReportRestoreError;
            var session = _narrative.Session;
            NovelSaveUI.Module?.Track(session);
            EUIManager.Instance.ShowMainPage(GamePages.EUINovelReaderPage, session, page =>
            {
                if (entry != _entryVersion || session.IsDisposed)
                { if (page != null) EUIManager.Instance.ClosePage(page); return; }
                if (page == null) { NovelSaveUI.Module?.ReportMessage("阅读页面加载失败，存档文件已保留"); ReturnToMenu(); return; }
                if (args is NovelPreparedGameRequest)
                {
                    try { session.CommitRestore(session.View); NovelSaveUI.Module?.ReportMessage("读档成功"); }
                    catch (System.Exception ex) { NovelSaveUI.Module?.ReportMessage("恢复提交失败：" + ex.Message); ReturnToMenu(); }
                }
            }, () => entry == _entryVersion && !session.IsDisposed);
        }

        // [EmberManaged:begin OnGameplayExit]
        protected override void OnGameplayExit()
        // [EmberManaged:end]
        {
            EUIManager.Instance.CloseAllPopups();
            NovelSaveUI.Module?.CancelLoad(); NovelSaveUI.Module?.Track(null);
            ++_entryVersion;
            if (_narrative != null) { _narrative.MenuRequested -= ReturnToMenu; _narrative.FatalRestoreError -= ReportRestoreError; _narrative.EndSession(); }
            EUIManager.Instance.ClosePageByDef(GamePages.EUINovelReaderPage);
            _narrative = null;
            base.OnGameplayExit();
        }
        protected override void OnGameplayPause() { _narrative?.Session?.Pause("GameplayOverlay"); }
        protected override void OnGameplayResume() { _narrative?.Session?.Resume("GameplayOverlay"); }
        private void ReturnToMenu() => GameLauncher.Instance.Fsm.TransitionTo<MainState>();
        private void ReportRestoreError(string message) => NovelSaveUI.Module?.ReportMessage("恢复后发生错误，已返回菜单，存档文件已保留：" + message);
    }
}
