// Generated by Ember Setup v0.3.0 (framework v0.12.6) — 框架演示代码（全文件框架所有）
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditorInternal;
using UnityEngine;

namespace Game.Module.Guide.Editor
{
    /// <summary>左侧排序、右侧按开始/结束阶段编辑的引导窗口。</summary>
    internal sealed class GuideEditorWindow : EditorWindow
    {
        #region 编辑器面板参数
        [SerializeField] private GuideDefine _define;
        [SerializeField] private int _selectedStep;
        #endregion

        // --------------------------------------------------------

        #region 内部参数
        private SerializedObject _serialized;
        private ReorderableList _steps;
        private Vector2 _listScroll;
        private Vector2 _detailScroll;
        private List<string> _issues;
        private Action _pendingAction;
        #endregion

        // --------------------------------------------------------

        #region 生命周期
        private void OnEnable()
        {
            minSize = new Vector2(820, 520);
            Undo.undoRedoPerformed += OnUndoRedo;
            Rebuild();
        }

        private void OnDisable()
        {
            Undo.undoRedoPerformed -= OnUndoRedo;
            _serialized?.Dispose();
            _serialized = null;
        }

        private void OnUndoRedo() { Rebuild(); Repaint(); }

        private void OnGUI()
        {
            DrawToolbar();
            if (!_define)
            {
                EditorGUILayout.HelpBox("选择已有 GuideDefine，或点击“新建引导”。也可在 Project 中双击引导定义打开。", MessageType.Info);
                return;
            }
            if (_serialized == null || _serialized.targetObject != _define) Rebuild();
            _serialized.Update();
            var editable = GuideEditorModel.CanEdit(_define);
            if (!editable) EditorGUILayout.HelpBox("当前只读：请退出运行模式，并选择 Assets 下可写的引导定义。", MessageType.Info);
            using (new EditorGUI.DisabledScope(!editable))
            using (new EditorGUILayout.HorizontalScope())
            {
                using (new EditorGUILayout.VerticalScope(GUILayout.Width(270)))
                {
                    _listScroll = EditorGUILayout.BeginScrollView(_listScroll);
                    _steps.DoLayoutList();
                    EditorGUILayout.EndScrollView();
                    using (new EditorGUILayout.HorizontalScope())
                    {
                        if (GUILayout.Button("新增步骤")) _pendingAction = () => AddStep(false);
                        using (new EditorGUI.DisabledScope(_selectedStep < 0 || _selectedStep >= _steps.count))
                            if (GUILayout.Button("复制选中")) _pendingAction = () => AddStep(true);
                    }
                    EditorGUILayout.LabelField("拖动把手排序；Ctrl+Z 撤销", EditorStyles.miniLabel);
                    EditorGUILayout.LabelField("保存只写当前引导资产", EditorStyles.miniLabel);
                }
                using (new EditorGUILayout.VerticalScope())
                {
                    _detailScroll = EditorGUILayout.BeginScrollView(_detailScroll);
                    GuideEditorFields.DrawCondition(_serialized.FindProperty("baseSkipAll"), "全局跳过条件", "未设置时不跳过整条引导");
                    var array = _serialized.FindProperty("guideSteps");
                    if (_selectedStep >= 0 && _selectedStep < array.arraySize)
                    {
                        EditorGUILayout.Space();
                        EditorGUILayout.LabelField($"步骤 {_selectedStep + 1} / {array.arraySize}", EditorStyles.boldLabel);
                        GuideEditorFields.DrawStep(array.GetArrayElementAtIndex(_selectedStep));
                    }
                    else EditorGUILayout.HelpBox("添加或选择一个步骤。", MessageType.Info);
                    if (_issues != null)
                    {
                        EditorGUILayout.LabelField("配置检查结果", EditorStyles.boldLabel);
                        if (_issues.Count == 0) EditorGUILayout.HelpBox("未发现常见配置问题，仍需进入游戏验证流程。", MessageType.Info);
                        foreach (var issue in _issues) EditorGUILayout.HelpBox(issue, MessageType.Warning);
                    }
                    EditorGUILayout.EndScrollView();
                }
            }
            if (_serialized.ApplyModifiedProperties()) _issues = null;
            if (_pendingAction == null) return;
            var action = _pendingAction;
            _pendingAction = null;
            action();
            Repaint();
        }
        #endregion

        // --------------------------------------------------------

        #region 内部方法
        [OnOpenAsset]
        private static bool OnOpenAsset(EntityId entityId, int line)
        {
            if (EditorUtility.EntityIdToObject(entityId) is not GuideDefine define) return false;
            Open(define);
            return true;
        }

        private void DrawToolbar()
        {
            using var toolbar = new EditorGUILayout.HorizontalScope(EditorStyles.toolbar);
            var selected = (GuideDefine)EditorGUILayout.ObjectField(_define, typeof(GuideDefine), false, GUILayout.MinWidth(180));
            if (selected != _define) { _define = selected; _selectedStep = 0; Rebuild(); }
            using (new EditorGUI.DisabledScope(EditorApplication.isPlayingOrWillChangePlaymode))
                if (GUILayout.Button("新建引导", EditorStyles.toolbarButton, GUILayout.Width(72))) CreateAsset();
            using (new EditorGUI.DisabledScope(!_define))
            {
                if (GUILayout.Button("定位", EditorStyles.toolbarButton, GUILayout.Width(45))) EditorGUIUtility.PingObject(_define);
                if (GUILayout.Button("检查配置", EditorStyles.toolbarButton, GUILayout.Width(72)))
                {
                    _serialized?.ApplyModifiedProperties();
                    _issues = GuideEditorModel.Validate(_define);
                }
            }
            using (new EditorGUI.DisabledScope(!GuideEditorModel.CanEdit(_define)))
                if (GUILayout.Button(_define && EditorUtility.IsDirty(_define) ? "保存 *" : "保存", EditorStyles.toolbarButton, GUILayout.Width(65)))
                {
                    _serialized?.ApplyModifiedProperties();
                    AssetDatabase.SaveAssetIfDirty(_define);
                }
        }

        private void Rebuild()
        {
            _serialized?.Dispose();
            _serialized = _define ? new SerializedObject(_define) : null;
            _issues = null;
            if (_serialized == null) { _steps = null; return; }
            _steps = new ReorderableList(_serialized, _serialized.FindProperty("guideSteps"), true, true, false, true)
            {
                elementHeight = 42,
                drawHeaderCallback = rect => EditorGUI.LabelField(rect, "引导步骤 · 按顺序执行"),
                drawElementCallback = (rect, index, active, focused) =>
                {
                    var step = _serialized.FindProperty("guideSteps").GetArrayElementAtIndex(index);
                    var name = step.FindPropertyRelative("name").stringValue;
                    EditorGUI.LabelField(new Rect(rect.x, rect.y + 3, rect.width, 20),
                        $"{index + 1}. {(string.IsNullOrWhiteSpace(name) ? "未命名步骤" : name)}", EditorStyles.boldLabel);
                    EditorGUI.LabelField(new Rect(rect.x, rect.y + 23, rect.width, 17),
                        step.FindPropertyRelative("needUpdate").boolValue ? "事件 + 每帧检查" : "事件驱动", EditorStyles.miniLabel);
                },
                onSelectCallback = list => { _selectedStep = list.index; GUI.FocusControl(null); },
                onReorderCallback = list => { _selectedStep = list.index; _issues = null; },
                onRemoveCallback = list =>
                {
                    if (list.index < 0 || list.index >= list.count) return;
                    if (!EditorUtility.DisplayDialog("删除引导步骤", $"删除第 {list.index + 1} 步？可用 Ctrl+Z 撤销。", "删除", "取消")) return;
                    list.serializedProperty.DeleteArrayElementAtIndex(list.index);
                    list.index = _selectedStep = list.count == 0 ? -1 : Mathf.Clamp(list.index, 0, list.count - 1);
                }
            };
            _steps.index = _selectedStep = _steps.count == 0 ? -1 : Mathf.Clamp(_selectedStep, 0, _steps.count - 1);
        }

        private void AddStep(bool copy)
        {
            GuideEditorModel.AddStep(_define, copy ? _selectedStep : -1);
            _selectedStep = copy ? _selectedStep + 1 : _define.guideSteps.Count - 1;
            Rebuild();
        }

        private void CreateAsset()
        {
            var path = EditorUtility.SaveFilePanelInProject("新建引导定义", "GuideDefine", "asset", "请选择项目 Assets 内的保存位置。");
            if (string.IsNullOrEmpty(path) || !path.StartsWith("Assets/", StringComparison.Ordinal)) return;
            path = AssetDatabase.GenerateUniqueAssetPath(path);
            var define = CreateInstance<GuideDefine>();
            AssetDatabase.CreateAsset(define, path);
            Undo.RegisterCreatedObjectUndo(define, "新建引导定义");
            _define = define;
            _selectedStep = -1;
            Rebuild();
            EditorGUIUtility.PingObject(define);
        }
        #endregion

        // --------------------------------------------------------

        #region 外部方法
        internal static void Open(GuideDefine define)
        {
            var window = GetWindow<GuideEditorWindow>("引导编辑器");
            if (define) { window._define = define; window._selectedStep = 0; window.Rebuild(); }
            window.Show();
        }
        #endregion
    }
}
