// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 框架设置弹窗页面逻辑（生成区文件，框架所有）
/*=============================================================
 * author       : DESKTOP-5SRUU55
 * prefab name  : EUISettingPanel
 * page name    : EUISettingPage
 * 本文件为框架生成（混合文件）：
 *   [EmberManaged] 块内 = 框架所有（生命周期 override，刷新时整块替换，勿改）；
 *   块外 = 用户级生命周期（XxxUser 方法），用户只改这里，永不触碰
 ==============================================================*/
using Ember.Basic;
using Ember.Core;
using Ember.UI;

namespace Game.UI
{
    public partial class EUISettingPage
    {
        // ── 框架生命周期（块内框架所有；每个 override 末尾调用对应的用户级钩子）──
        // [EmberManaged:begin Lifecycle]
        private const string TAG = LogTags.Game + "." + nameof(EUISettingPage);

        public override void OnInit()
        {
            base.OnInit();

            Btn_Close.onClick.AddListener(() =>
                GameLauncher.Instance.Fsm.Pop());

            OnInitUser();
        }

        public override void OnOpen(object param)
        {
            base.OnOpen(param);

            var context = param is SettingsContext ctx ? ctx : SettingsContext.Main;
            Txt_NowScene.text = context switch
            {
                SettingsContext.Main     => "当前场景：主界面",
                SettingsContext.Gameplay => "当前场景：玩法中",
                _                        => "当前场景：未知",
            };

            OnOpenUser(param);
        }

        public override void OnShow()
        {
            base.OnShow();
            OnShowUser();
        }

        public override void OnHide()
        {
            base.OnHide();
            OnHideUser();
        }

        public override void OnClose()
        {
            base.OnClose();
            OnCloseUser();
        }

        public override void OnDispose()
        {
            EmberDebug.Log(TAG, "EUISettingPage 清理");
            Btn_Close.onClick.RemoveAllListeners();
            base.OnDispose();
            OnDisposeUser();
        }
        // [EmberManaged:end]

        // ── 用户级生命周期（块外用户区，永不触碰）──

        /// <summary>用户初始化钩子：框架 OnInit 结束时调用。</summary>
        private void OnInitUser()
        {
            InitScreenPreferences();
            NovelTextSpeed.onValueChanged.AddListener(SaveNovelPreferences);
            NovelAutoInterval.onValueChanged.AddListener(SaveNovelPreferences);
            NovelBgmVolume.onValueChanged.AddListener(SaveNovelPreferences);
            NovelSfxVolume.onValueChanged.AddListener(SaveNovelPreferences);
            NovelVoiceVolume.onValueChanged.AddListener(SaveNovelPreferences);
        }

        /// <summary>用户打开钩子：框架 OnOpen 结束时调用。</summary>
        private void OnOpenUser(object param)
        {
            _novelSettingsPause?.Dispose();
            if (EmberModuleCollector.Instance.TryGetModule(out Game.Narrative.NarrativeModule narrative))
                _novelSettingsPause = narrative.Session?.AcquirePause("Settings");
            _novelPreferences = NovelSaveUI.Module;
            var a = _novelPreferences?.Account;
            if (a != null)
            {
                NovelTextSpeed.SetValueWithoutNotify(a.TextSpeed); NovelAutoInterval.SetValueWithoutNotify(a.AutoInterval);
                NovelBgmVolume.SetValueWithoutNotify(a.BgmVolume); NovelSfxVolume.SetValueWithoutNotify(a.SfxVolume); NovelVoiceVolume.SetValueWithoutNotify(a.VoiceVolume);
                _novelPreferences.Changed += RefreshNovelPreferences;
            }
            foreach (var slider in new[] { NovelTextSpeed, NovelAutoInterval, NovelBgmVolume, NovelSfxVolume, NovelVoiceVolume }) slider.interactable = a != null;
            RefreshNovelPreferences();
        }

        /// <summary>用户显示钩子：框架 OnShow 结束时调用。</summary>
        private void OnShowUser()
        {
            // 页面变为可见
        }

        /// <summary>用户隐藏钩子：框架 OnHide 结束时调用。</summary>
        private void OnHideUser()
        {
            // 页面被隐藏
        }

        /// <summary>用户关闭钩子：框架 OnClose 结束时调用。</summary>
        private void OnCloseUser()
        {
            ReleaseNovelPreferences();
        }

        /// <summary>用户释放钩子：框架 OnDispose 结束时调用。</summary>
        private void OnDisposeUser()
        {
            ReleaseNovelPreferences();
            DisposeScreenPreferences();
            NovelTextSpeed.onValueChanged.RemoveListener(SaveNovelPreferences); NovelAutoInterval.onValueChanged.RemoveListener(SaveNovelPreferences);
            NovelBgmVolume.onValueChanged.RemoveListener(SaveNovelPreferences); NovelSfxVolume.onValueChanged.RemoveListener(SaveNovelPreferences); NovelVoiceVolume.onValueChanged.RemoveListener(SaveNovelPreferences);
        }
        private System.IDisposable _novelSettingsPause;
        private Game.NovelSave.NovelSaveModule _novelPreferences;
        private void ReleaseNovelPreferences()
        {
            _novelSettingsPause?.Dispose(); _novelSettingsPause = null;
            if (_novelPreferences != null) _novelPreferences.Changed -= RefreshNovelPreferences;
            _novelPreferences = null;
        }
        private void SaveNovelPreferences(float value)
        {
            _novelPreferences?.SavePreferences(NovelTextSpeed.value, NovelAutoInterval.value, NovelBgmVolume.value, NovelSfxVolume.value, NovelVoiceVolume.value);
            RefreshNovelPreferences();
        }
        private void RefreshNovelPreferences()
        {
            RefreshScreenPreferences();
            NovelTextSpeedValue.text = $"{NovelTextSpeed.value:0} 字/秒";
            NovelAutoIntervalValue.text = $"{NovelAutoInterval.value:0.0} 秒";
            NovelBgmVolumeValue.text = $"{NovelBgmVolume.value:P0}";
            NovelSfxVolumeValue.text = $"{NovelSfxVolume.value:P0}";
            NovelVoiceVolumeValue.text = $"{NovelVoiceVolume.value:P0}";
            string EffectLabel(float value) => UnityEngine.Mathf.RoundToInt(value) switch { 1 => "减弱", 2 => "关闭", _ => "正常" };
            NovelShakePreferenceValue.text = EffectLabel(NovelShakePreference.value);
            NovelFlashPreferenceValue.text = EffectLabel(NovelFlashPreference.value);
            NovelPreferenceStatus.text = _novelPreferences?.Message ?? string.Empty;
        }
    }
}
