// Generated by Ember Setup v{EMBED_VERSION} — 默认开屏动画（无动画，立即完成）
// 挂在 MainScene 的 GameObject 上。自定义动画：继承 EUIMainAnimationStarter，
// override PlayOpeningAnimation 返回动画 UniTask，然后替换场景中的本组件。
using Cysharp.Threading.Tasks;

namespace {NAMESPACE}
{
    public sealed class EUIDefaultMainAnimation : EUIMainAnimationStarter
    {
        protected override UniTask PlayOpeningAnimation()
        {
            // 默认：无开场动画，立即完成
            return UniTask.CompletedTask;
        }
    }
}
