// Generated by Ember Setup v0.3.0 (framework v0.12.6) — 框架演示代码（全文件框架所有）
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Game.Module.Guide.Editor
{
    /// <summary>使用 SerializedProperty 绘制中文条件、事件和执行器，统一保留 Undo。</summary>
    internal static class GuideEditorFields
    {
        #region 内部参数

        private static readonly Dictionary<string, string> Labels = new()
        {
            ["name"] = "步骤用途", ["needUpdate"] = "每帧检查条件",
            ["pagePath"] = "目标页面路径", ["prefabPath"] = "页面 Prefab 路径",
            ["ctrlName"] = "目标节点名", ["tips"] = "小手提示文字", ["message"] = "文字内容",
            ["handDelay"] = "小手延迟（秒）", ["maskColor"] = "遮罩颜色",
            ["clickMaskToCancel"] = "点击遮罩取消引导", ["duration"] = "持续秒数（负数常驻）",
            ["seconds"] = "等待秒数", ["layer"] = "UI 层级", ["pageType"] = "页面类型",
            ["key"] = "自定义事件编号", ["guideId"] = "引导编号", ["isShowing"] = "要求页面正在显示",
            ["intParamIndex"] = "整数参数下标（从 0 开始）", ["op"] = "比较方式", ["value"] = "比较值"
        };

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        private static void DrawList(SerializedProperty list, string title, bool executors)
        {
            using var box = new EditorGUILayout.VerticalScope(EditorStyles.helpBox);
            list.isExpanded = EditorGUILayout.Foldout(list.isExpanded, $"{title} ({list.arraySize})", true);
            if (!list.isExpanded) return;
            for (var i = 0; i < list.arraySize; i++)
            {
                var item = list.GetArrayElementAtIndex(i);
                using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox))
                {
                    var value = item.managedReferenceValue;
                    if (value == null)
                    {
                        if (GUILayout.Button("创建条目"))
                            item.managedReferenceValue = executors
                                ? new GuideExecutor { executeType = GuideExecuteType.CloseHand }
                                : new GuideEvent { eventType = GuideEventType.OnGuideMaskClick };
                    }
                    else
                    {
                        var enumField = item.FindPropertyRelative(executors ? "executeType" : "eventType");
                        var param = item.FindPropertyRelative(executors ? "executeParam" : "eventParam");
                        var offset = executors ? 1 : 0;
                        EditorGUI.BeginChangeCheck();
                        var chosen = EditorGUILayout.Popup($"#{i + 1} 类型", enumField.intValue - offset,
                            executors ? GuideEditorModel.ExecutorNames : GuideEditorModel.EventNames);
                        if (EditorGUI.EndChangeCheck())
                        {
                            enumField.intValue = chosen + offset;
                            object prototype = executors
                                ? new GuideExecutor { executeType = (GuideExecuteType)(chosen + offset) }
                                : new GuideEvent { eventType = (GuideEventType)chosen };
                            var expected = GuideEditorModel.ParameterType(prototype);
                            // 相同参数结构（如页面打开/关闭）保留已填内容。
                            if (param.managedReferenceValue?.GetType() != expected)
                                param.managedReferenceValue = expected == null ? null : Activator.CreateInstance(expected);
                        }
                        else DrawParameter(param, GuideEditorModel.ParameterType(value));
                    }
                    if (ListButtons(list, i)) return;
                }
            }
            if (GUILayout.Button(executors ? "添加执行器" : "添加事件"))
                Append(list, executors ? new GuideExecutor { executeType = GuideExecuteType.CloseHand }
                    : new GuideEvent { eventType = GuideEventType.OnGuideMaskClick });
        }

        private static bool ListButtons(SerializedProperty list, int index)
        {
            using var row = new EditorGUILayout.HorizontalScope();
            GUILayout.FlexibleSpace();
            using (new EditorGUI.DisabledScope(index == 0))
                if (GUILayout.Button("上移", GUILayout.Width(48))) { list.MoveArrayElement(index, index - 1); return true; }
            using (new EditorGUI.DisabledScope(index == list.arraySize - 1))
                if (GUILayout.Button("下移", GUILayout.Width(48))) { list.MoveArrayElement(index, index + 1); return true; }
            if (!GUILayout.Button("移除", GUILayout.Width(48))) return false;
            list.DeleteArrayElementAtIndex(index);
            return true;
        }

        private static void Append(SerializedProperty list, object value)
        {
            var index = list.arraySize++;
            var item = list.GetArrayElementAtIndex(index);
            item.managedReferenceValue = value;
            item.isExpanded = true;
        }

        private static void DrawParameter(SerializedProperty parameter, Type expected)
        {
            var current = parameter.managedReferenceValue;
            if (expected != null && current?.GetType() != expected)
            {
                EditorGUILayout.HelpBox("参数缺失或类型不匹配。重建会替换旧参数，可撤销。", MessageType.Warning);
                if (GUILayout.Button("创建 / 重建参数")) parameter.managedReferenceValue = Activator.CreateInstance(expected);
                return;
            }
            if (current == null) return;
            if (expected == null)
                EditorGUILayout.HelpBox("此类型不需要参数；现有参数保留，可切换类型或撤销。", MessageType.Info);
            var child = parameter.Copy();
            var end = parameter.GetEndProperty();
            if (!child.NextVisible(true)) return;
            while (!SerializedProperty.EqualContents(child, end))
            {
                Field(child);
                if (!child.NextVisible(false)) break;
            }
        }

        private static void Field(SerializedProperty field)
        {
            if (field.name == "eventType")
            {
                EditorGUI.BeginChangeCheck();
                var selected = EditorGUILayout.Popup("触发事件", field.intValue, GuideEditorModel.EventNames);
                if (EditorGUI.EndChangeCheck()) field.intValue = selected;
                return;
            }
            if (field.name == "op")
            {
                EditorGUI.BeginChangeCheck();
                var selected = EditorGUILayout.Popup("比较方式", field.intValue, new[] { "等于", "大于", "小于", "大于等于", "小于等于" });
                if (EditorGUI.EndChangeCheck()) field.intValue = selected;
                return;
            }
            var label = Labels.TryGetValue(field.name, out var chinese) ? chinese : field.displayName;
            if (field.propertyType == SerializedPropertyType.String && (field.name == "message" || field.name == "tips"))
            {
                EditorGUILayout.LabelField(label);
                field.stringValue = EditorGUILayout.TextArea(field.stringValue, GUILayout.MinHeight(45));
            }
            else EditorGUILayout.PropertyField(field, new GUIContent(label), true);
            if (field.name == "pagePath" || field.name == "prefabPath")
            {
                EditorGUILayout.LabelField("填写 EUIPageDef.PrefabPath，与页面定义保持一致。", EditorStyles.miniLabel);
                if (GUILayout.Button("选择页面（中文用途）")) GuideEditorPicker.ShowPages(field);
            }
            if (field.name == "ctrlName")
            {
                EditorGUILayout.LabelField("填写 Prefab 中的实际节点名（当前运行器按节点名递归查找）。", EditorStyles.miniLabel);
                if (GUILayout.Button("选择目标节点")) GuideEditorPicker.ShowControls(field);
            }
        }

        #endregion

        // --------------------------------------------------------

        #region 外部方法

        internal static void DrawStep(SerializedProperty step)
        {
            Field(step.FindPropertyRelative("name"));
            Field(step.FindPropertyRelative("needUpdate"));
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("开始阶段 · 等待 → 执行", EditorStyles.boldLabel);
            DrawList(step.FindPropertyRelative("startEvents"), "开始事件（唤醒条件检查）", false);
            DrawCondition(step.FindPropertyRelative("startConditionsToSkipAll"), "跳过整条引导", "未设置时不跳过");
            DrawCondition(step.FindPropertyRelative("startConditionsToSkip"), "跳过当前步骤", "未设置时不跳过");
            DrawCondition(step.FindPropertyRelative("startConditionsToSuccess"), "开始执行条件", "未设置时直接开始");
            DrawList(step.FindPropertyRelative("startExecutors"), "开始执行器（按顺序执行）", true);
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("结束阶段 · 执行 → 下一步", EditorStyles.boldLabel);
            DrawList(step.FindPropertyRelative("endEvents"), "结束事件（唤醒完成检查）", false);
            DrawCondition(step.FindPropertyRelative("endConditionsToFinishAll"), "完成整条引导", "未设置时不提前完成");
            DrawCondition(step.FindPropertyRelative("endConditionsToCancelAll"), "取消整条引导", "未设置时不取消");
            DrawCondition(step.FindPropertyRelative("endConditionsToCancel"), "取消并重试当前步骤", "未设置时不取消");
            DrawCondition(step.FindPropertyRelative("endConditionsToSuccess"), "完成当前步骤", "未设置时立即完成，不会等待事件");
            DrawList(step.FindPropertyRelative("endExecutors"), "结束执行器（按顺序执行）", true);
        }

        internal static void DrawCondition(SerializedProperty property, string title, string emptyHint, int depth = 0)
        {
            if (depth > 12) { EditorGUILayout.HelpBox("条件嵌套过深或存在循环，请先检查配置。", MessageType.Warning); return; }
            using var box = new EditorGUILayout.VerticalScope(EditorStyles.helpBox);
            var value = property.managedReferenceValue;
            var selection = value switch
            {
                null => 0,
                GuideCondition c when (int)c.conditionType >= 1 && (int)c.conditionType <= 6 => (int)c.conditionType,
                GuideConditionGroup g => g.logicOperator == LogicOperator.And ? 7 : 8,
                _ => -1
            };
            EditorGUI.BeginChangeCheck();
            var chosen = EditorGUILayout.Popup(title, selection, GuideEditorModel.ConditionNames);
            if (EditorGUI.EndChangeCheck())
            {
                // 切换 AND/OR 时保留已有子条件；其他类型替换可通过 Undo 恢复。
                if (value is GuideConditionGroup && chosen >= 7)
                    property.FindPropertyRelative("logicOperator").intValue = chosen == 7 ? 0 : 1;
                else property.managedReferenceValue = GuideEditorModel.CreateCondition(chosen);
                return;
            }
            if (value == null) { EditorGUILayout.LabelField(emptyHint, EditorStyles.miniLabel); return; }
            property.isExpanded = EditorGUILayout.Foldout(property.isExpanded, "参数 / 子条件", true);
            if (!property.isExpanded) return;
            if (value is GuideConditionGroup)
            {
                var list = property.FindPropertyRelative("conditions");
                for (var i = 0; i < list.arraySize; i++)
                {
                    DrawCondition(list.GetArrayElementAtIndex(i), $"子条件 {i + 1}", "空子条件会被忽略", depth + 1);
                    if (ListButtons(list, i)) return;
                }
                if (GUILayout.Button("添加子条件")) Append(list, GuideEditorModel.CreateCondition(1));
            }
            else if (value is GuideCondition)
                DrawParameter(property.FindPropertyRelative("conditionParams"), GuideEditorModel.ParameterType(value));
            else EditorGUILayout.PropertyField(property, new GUIContent("自定义条件"), true);
        }

        #endregion
    }
}
