// Copyright (c) 2026 Ember Unity Framework. All rights reserved.

using System;
using System.IO;

using Ember.Core.Editor;

using NUnit.Framework;

using UnityEditor;
using UnityEngine;

namespace Ember.UI.Tests
{
    /// <summary>消费端活动模板与旧部署记录迁移规则测试。</summary>
    public class EmberTemplateDeploymentEditTests
    {
        #region 外部方法

        [Test]
        public void ActiveDeployment_ExplicitIdShouldResolveMatchingRecord()
        {
            var data = CreateData("platformer2d", "base", "platformer2d");

            var active = EmberProjectSetup.ResolveActiveDeployment(data);

            Assert.IsNotNull(active);
            Assert.AreEqual("platformer2d", active.templateId);
        }

        [Test]
        public void ActiveDeployment_LegacySingleRecordShouldResolveWithoutMutation()
        {
            var data = CreateData(null, "base");

            var active = EmberProjectSetup.ResolveActiveDeployment(data);

            Assert.IsNotNull(active);
            Assert.AreEqual("base", active.templateId);
            Assert.IsNull(data.activeTemplateId);
        }

        [Test]
        public void ActiveDeployment_LegacyMultipleRecordsShouldRemainAmbiguous()
        {
            var data = CreateData(null, "base", "platformer2d");

            Assert.IsNull(EmberProjectSetup.ResolveActiveDeployment(data));
            StringAssert.Contains(
                "明确认定当前活动模板",
                EmberProjectSetup.GetDeploymentBlockReason(data, "base"));
        }

        [Test]
        public void DeploymentGate_FirstDeploymentShouldAllowAnyTemplate()
        {
            Assert.IsNull(EmberProjectSetup.GetDeploymentBlockReason(
                new DeployedTemplatesData(),
                "platformer2d"));
        }

        [Test]
        public void DeploymentGate_CurrentActiveTemplateShouldAllowRepair()
        {
            var data = CreateData("base", "base", "platformer2d");

            Assert.IsNull(EmberProjectSetup.GetDeploymentBlockReason(data, "base"));
        }

        [Test]
        public void DeploymentGate_DifferentTemplateShouldRequireConfirmedDeployment()
        {
            var data = CreateData("base", "base", "platformer2d");

            var reason = EmberProjectSetup.GetDeploymentBlockReason(data, "platformer2d");

            StringAssert.Contains("确认后部署", reason);
        }

        [Test]
        public void DeploymentGate_BrokenExplicitActiveIdShouldBlock()
        {
            var data = CreateData("missing", "base");

            var reason = EmberProjectSetup.GetDeploymentBlockReason(data, "base");

            StringAssert.Contains("没有对应记录", reason);
        }

        [Test]
        public void ReplacementDeploymentGate_DifferentActiveTemplateShouldAllowDeployment()
        {
            var data = CreateData("base", "base");

            Assert.IsNull(EmberProjectSetup.GetReplacementDeploymentBlockReason(
                data,
                "source3d-2p5d"));
        }

        [Test]
        public void ReplacementDeploymentGate_SameActiveTemplateShouldAllowExplicitRedeploy()
        {
            var data = CreateData("source3d-2p5d", "source3d-2p5d");

            Assert.IsNull(EmberProjectSetup.GetReplacementDeploymentBlockReason(
                data,
                "source3d-2p5d"));
        }

        [Test]
        public void ReplacementDeploymentGate_FirstDeploymentShouldUseInitialize()
        {
            var reason = EmberProjectSetup.GetReplacementDeploymentBlockReason(
                new DeployedTemplatesData(),
                "source3d-2p5d");

            StringAssert.Contains("直接初始化", reason);
        }

        [Test]
        public void ReplacementDeploymentGate_AmbiguousLegacyRecordsShouldBlock()
        {
            var data = CreateData(null, "base", "source3d-2p5d");

            var reason = EmberProjectSetup.GetReplacementDeploymentBlockReason(
                data,
                "source3d-2p5d");

            StringAssert.Contains("明确认定当前活动模板", reason);
        }

        [Test]
        public void ReplacementDeployment_ReplacesManagedDirectoriesWithoutTouchingExternalContent()
        {
            string root = Path.Combine(
                Path.GetTempPath(),
                "EmberTemplateDeployTests-" + Guid.NewGuid().ToString("N"));
            string projectRoot = Path.Combine(root, "Project");
            string templateAssets = Path.Combine(root, "Template", "Assets");
            try
            {
                Write(projectRoot, "Assets/Game/Old.txt", "old");
                Write(projectRoot, "Assets/Art/Keep.txt", "keep");
                Write(
                    templateAssets,
                    "Game/New.cs",
                    "// Generated by Ember Setup v0.1.0 (framework v0.10.0) — framework\nclass New {}\n");
                Write(templateAssets, "Resources/Template.txt", "resource");
                var template = new TemplateInfo
                {
                    id = "source3d-2p5d",
                    schemaVersion = EmberTemplateInheritanceEngine.CurrentSchemaVersion,
                    version = "0.2.6",
                    frameworkVersion = "0.11.3",
                    contentHash = EmberTemplateInheritanceEngine.ComputeTemplateContentHash(
                        templateAssets)
                };

                int deployed = EmberProjectSetup.ReplaceManagedDirectoriesFromTemplate(
                    projectRoot,
                    templateAssets,
                    template);

                Assert.Greater(deployed, 0);
                Assert.IsFalse(File.Exists(Path.Combine(projectRoot, "Assets/Game/Old.txt")));
                StringAssert.Contains(
                    "v0.2.6 (framework v0.11.3)",
                    File.ReadAllText(Path.Combine(projectRoot, "Assets/Game/New.cs")));
                Assert.AreEqual(
                    "keep",
                    File.ReadAllText(Path.Combine(projectRoot, "Assets/Art/Keep.txt")));
            }
            finally
            {
                if (Directory.Exists(root)) Directory.Delete(root, true);
            }
        }

        [Test]
        public void ReplacementDeployment_ExternalGuidCollisionShouldBlockBeforeMutation()
        {
            const string collisionGuid = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
            string root = Path.Combine(
                Path.GetTempPath(),
                "EmberTemplateGuidTests-" + Guid.NewGuid().ToString("N"));
            string projectRoot = Path.Combine(root, "Project");
            string templateAssets = Path.Combine(root, "Template", "Assets");
            try
            {
                Write(projectRoot, "Assets/Game/Keep.txt", "unchanged");
                Write(projectRoot, "Assets/Scenes/SampleScene.unity", "scene");
                Write(
                    projectRoot,
                    "Assets/Scenes/SampleScene.unity.meta",
                    $"fileFormatVersion: 2\nguid: {collisionGuid}\n");
                Write(templateAssets, "Game/Scenes/GameplayScene.unity", "scene");
                Write(
                    templateAssets,
                    "Game/Scenes/GameplayScene.unity.meta",
                    $"fileFormatVersion: 2\nguid: {collisionGuid}\n");
                var template = new TemplateInfo
                {
                    id = "source3d-2p5d",
                    schemaVersion = EmberTemplateInheritanceEngine.CurrentSchemaVersion,
                    version = "0.2.7",
                    frameworkVersion = "0.11.4",
                    contentHash = EmberTemplateInheritanceEngine.ComputeTemplateContentHash(
                        templateAssets)
                };

                var exception = Assert.Throws<InvalidOperationException>(() =>
                    EmberProjectSetup.ReplaceManagedDirectoriesFromTemplate(
                        projectRoot,
                        templateAssets,
                        template));

                StringAssert.Contains("GUID", exception.Message);
                StringAssert.Contains("Assets/Scenes/SampleScene.unity", exception.Message);
                Assert.AreEqual(
                    "unchanged",
                    File.ReadAllText(Path.Combine(projectRoot, "Assets/Game/Keep.txt")));
                Assert.IsFalse(File.Exists(Path.Combine(
                    projectRoot,
                    "Assets/Game/Scenes/GameplayScene.unity")));
            }
            finally
            {
                if (Directory.Exists(root)) Directory.Delete(root, true);
            }
        }

        [Test]
        public void ReplacementDeployment_ManagedGuidOwnerShouldBeReplacedNotBlocked()
        {
            const string sharedGuid = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
            string root = Path.Combine(
                Path.GetTempPath(),
                "EmberTemplateGuidTests-" + Guid.NewGuid().ToString("N"));
            string projectRoot = Path.Combine(root, "Project");
            string templateAssets = Path.Combine(root, "Template", "Assets");
            try
            {
                Write(projectRoot, "Assets/Game/Old.asset", "old");
                Write(
                    projectRoot,
                    "Assets/Game/Old.asset.meta",
                    $"fileFormatVersion: 2\nguid: {sharedGuid}\n");
                Write(templateAssets, "Game/New.asset", "new");
                Write(
                    templateAssets,
                    "Game/New.asset.meta",
                    $"fileFormatVersion: 2\nguid: {sharedGuid}\n");
                var template = new TemplateInfo
                {
                    id = "base",
                    schemaVersion = EmberTemplateInheritanceEngine.CurrentSchemaVersion,
                    version = "0.5.6",
                    frameworkVersion = "0.11.4",
                    contentHash = EmberTemplateInheritanceEngine.ComputeTemplateContentHash(
                        templateAssets)
                };

                EmberProjectSetup.ReplaceManagedDirectoriesFromTemplate(
                    projectRoot,
                    templateAssets,
                    template);

                Assert.IsFalse(File.Exists(Path.Combine(projectRoot, "Assets/Game/Old.asset")));
                Assert.AreEqual(
                    "new",
                    File.ReadAllText(Path.Combine(projectRoot, "Assets/Game/New.asset")));
            }
            finally
            {
                if (Directory.Exists(root)) Directory.Delete(root, true);
            }
        }

        [Test]
        public void AdditiveDeployment_ExternalGuidCollisionShouldBlockButMatchingPathShouldPass()
        {
            const string sharedGuid = "cccccccccccccccccccccccccccccccc";
            string root = Path.Combine(
                Path.GetTempPath(),
                "EmberTemplateGuidTests-" + Guid.NewGuid().ToString("N"));
            string projectRoot = Path.Combine(root, "Project");
            string templateAssets = Path.Combine(root, "Template", "Assets");
            try
            {
                Write(templateAssets, "Game/Config.asset", "template");
                Write(
                    templateAssets,
                    "Game/Config.asset.meta",
                    $"fileFormatVersion: 2\nguid: {sharedGuid}\n");
                Write(projectRoot, "Assets/Game/Config.asset", "existing");
                Write(
                    projectRoot,
                    "Assets/Game/Config.asset.meta",
                    $"fileFormatVersion: 2\nguid: {sharedGuid}\n");

                Assert.IsNull(EmberProjectSetup.GetTemplateGuidCollisionBlockReason(
                    projectRoot,
                    templateAssets,
                    false));

                Write(projectRoot, "Assets/Art/Conflicting.asset", "external");
                Write(
                    projectRoot,
                    "Assets/Art/Conflicting.asset.meta",
                    $"fileFormatVersion: 2\nguid: {sharedGuid}\n");

                string reason = EmberProjectSetup.GetTemplateGuidCollisionBlockReason(
                    projectRoot,
                    templateAssets,
                    false);

                StringAssert.Contains("Assets/Art/Conflicting.asset", reason);
            }
            finally
            {
                if (Directory.Exists(root)) Directory.Delete(root, true);
            }
        }

        [TestCase(UnityEditor.PackageManager.PackageSource.Embedded, true)]
        [TestCase(UnityEditor.PackageManager.PackageSource.Git, false)]
        [TestCase(UnityEditor.PackageManager.PackageSource.Registry, false)]
        public void TemplateDevelopment_OnlyEmbeddedPackageSourceShouldBeAllowed(
            UnityEditor.PackageManager.PackageSource source,
            bool expected)
        {
            Assert.AreEqual(
                expected,
                EmberProjectSetup.IsTemplateDevelopmentSource(source));
        }

        [Test]
        public void DeploymentJson_LegacyFormatShouldRemainReadable()
        {
            const string json =
                "{\"records\":[{\"templateId\":\"base\",\"version\":\"0.5.0\"}]}";

            var data = JsonUtility.FromJson<DeployedTemplatesData>(json);
            var active = EmberProjectSetup.ResolveActiveDeployment(data);

            Assert.IsNull(data.activeTemplateId);
            Assert.AreEqual("base", active.templateId);
        }

        [Test]
        public void DeploymentJson_ActiveTemplateIdShouldRoundTrip()
        {
            var source = CreateData("base", "base");

            var roundTrip = JsonUtility.FromJson<DeployedTemplatesData>(
                JsonUtility.ToJson(source));

            Assert.AreEqual("base", roundTrip.activeTemplateId);
            Assert.AreEqual("base", EmberProjectSetup.ResolveActiveDeployment(roundTrip).templateId);
        }

        [Test]
        public void UnifiedSetupWindow_ShouldOwnOnlyProjectCenterMenuEntry()
        {
            var setupMethod = typeof(EmberSetupWindow).GetMethod(
                nameof(EmberSetupWindow.ShowWindow));
            var setupMenus = setupMethod.GetCustomAttributes(typeof(MenuItem), false);
            Assert.AreEqual(1, setupMenus.Length);
            Assert.AreEqual("Ember/项目中心", ((MenuItem)setupMenus[0]).menuItem);

            var legacyType = typeof(EmberSetupWindow).Assembly.GetType(
                "Ember.Core.Editor.EmberTemplateEditorWindow");
            var legacyMethod = legacyType.GetMethod("ShowWindow");
            Assert.AreEqual(0, legacyMethod.GetCustomAttributes(typeof(MenuItem), false).Length);
            var legacyValidationMethod = typeof(EmberProjectSetup).GetMethod(
                nameof(EmberProjectSetup.ValidateGeneratedFiles));
            Assert.IsNotNull(legacyValidationMethod);
            Assert.AreEqual(0, legacyValidationMethod.GetCustomAttributes(typeof(MenuItem), false).Length);
            Assert.IsNotNull(typeof(EmberSetupWindow).Assembly.GetType(
                "Ember.Core.Editor.EmberProjectSetupPanel"));
            Assert.IsNotNull(typeof(EmberSetupWindow).Assembly.GetType(
                "Ember.Core.Editor.EmberTemplateDevelopmentPanel"));
        }

        [TestCase(null, "source3d-2p5d", false)]
        [TestCase("", "source3d-2p5d", false)]
        [TestCase("base", "source3d-2p5d", false)]
        [TestCase("source3d-2p5d", "source3d-2p5d", true)]
        public void TemplateSync_AutoReloadShouldOnlyTargetActiveEditingCopy(
            string editingTemplateId,
            string syncedTemplateId,
            bool expected)
        {
            var editing = editingTemplateId == null
                ? null
                : new EditingTemplateRecord { templateId = editingTemplateId };

            Assert.AreEqual(
                expected,
                EmberTemplateDevelopmentPanel.ShouldAutoReloadEditingCopyAfterSync(
                    editing,
                    syncedTemplateId));
        }

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        private static DeployedTemplatesData CreateData(
            string activeTemplateId,
            params string[] templateIds)
        {
            var data = new DeployedTemplatesData { activeTemplateId = activeTemplateId };
            foreach (var templateId in templateIds)
            {
                data.records.Add(new DeployedTemplateRecord
                {
                    templateId = templateId,
                    version = "0.1.0",
                    frameworkVersion = "0.11.0"
                });
            }
            return data;
        }

        private static void Write(string root, string relativePath, string contents)
        {
            string path = Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, contents, new System.Text.UTF8Encoding(false));
        }

        #endregion
    }
}
