// Generated by Ember Setup v0.3.0 (framework v0.12.6) — 框架演示代码（全文件框架所有）
using System;
using System.Reflection;
using Ember.Basic;
using Ember.Core;
using UnityEditor;

namespace Game.Module.Guide.Editor
{
    /// <summary>顶部菜单跟随模块的编译后装配标记，不访问或创建模块单例。</summary>
    internal static class GuideEditorMenu
    {
        #region 内部参数

        private const string MENU_PATH = "Ember/引导/引导编辑器";
        private const BindingFlags MENU_FLAGS = BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic;

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        [InitializeOnLoadMethod]
        private static void ScheduleRefresh()
        {
            // 等 Unity 完成本次脚本重载的静态菜单重建后再同步；无需每帧轮询。
            EditorApplication.delayCall -= RefreshMenu;
            EditorApplication.delayCall += RefreshMenu;
        }

        private static void RefreshMenu()
        {
            var enabled = typeof(GuideModule).GetCustomAttribute<EmberModuleAttribute>(false)?.Enabled == true;
            try
            {
                // MenuItem 的验证函数只能置灰；动态显示/隐藏使用 Unity 的内部菜单 API。
                // 签名参考 UnityCsReference/Editor/Mono/Menu.bindings.cs；反射隔离版本差异。
                var menuType = typeof(Menu);
                var exists = menuType.GetMethod("MenuItemExists", MENU_FLAGS, null, new[] { typeof(string) }, null);
                var remove = menuType.GetMethod("RemoveMenuItem", MENU_FLAGS, null, new[] { typeof(string) }, null);
                var add = menuType.GetMethod("AddMenuItem", MENU_FLAGS, null,
                    new[] { typeof(string), typeof(string), typeof(bool), typeof(int), typeof(Action), typeof(Func<bool>) }, null);
                if (exists == null || remove == null || add == null)
                    throw new MissingMethodException("当前 Unity 版本缺少动态菜单 API。");

                var registered = (bool)exists.Invoke(null, new object[] { MENU_PATH });
                if (!enabled)
                {
                    if (registered) remove.Invoke(null, new object[] { MENU_PATH });
                    return;
                }
                if (registered) return;
                add.Invoke(null, new object[]
                {
                    MENU_PATH, string.Empty, false, 1000,
                    (Action)(() => GuideEditorWindow.Open(Selection.activeObject as GuideDefine)),
                    (Func<bool>)(() => true)
                });
            }
            catch (Exception exception)
            {
                EmberDebug.LogWarning("Game.Guide.Editor", "引导编辑器菜单同步失败："
                    + (exception.InnerException ?? exception).Message);
            }
        }

        #endregion
    }
}
