// Generated by Ember Setup v0.3.0 (framework v0.12.6) — 框架演示代码（全文件框架所有）
using System;
using System.Reflection;
using Ember.UI;
using Ember.UIExtension;
using Game.UI;
using UnityEditor;
using UnityEngine;

namespace Game.Module.Guide.Editor
{
    /// <summary>从当前业务页面定义选择路径，并按运行器实际查找方式选择节点。</summary>
    internal static class GuideEditorPicker
    {
        #region 内部方法

        private static void SetValue(UnityEngine.Object target, string path, string value, string expected, EUIPageDef definition = null)
        {
            if (target is not GuideDefine define || !GuideEditorModel.CanEdit(define)) return;
            using var serialized = new SerializedObject(target);
            var field = serialized.FindProperty(path);
            // 菜单打开期间目标改变时不覆盖新内容。
            if (field == null || field.propertyType != SerializedPropertyType.String || field.stringValue != expected) return;
            field.stringValue = value;
            if (definition != null && path.EndsWith(".prefabPath", StringComparison.Ordinal))
            {
                var parent = path.Substring(0, path.LastIndexOf('.'));
                var layer = serialized.FindProperty(parent + ".layer");
                var pageType = serialized.FindProperty(parent + ".pageType");
                if (layer != null) layer.intValue = definition.Layer;
                if (pageType != null) pageType.intValue = (int)definition.PageType;
            }
            serialized.ApplyModifiedProperties();
        }

        #endregion

        // --------------------------------------------------------

        #region 外部方法

        internal static void ShowPages(SerializedProperty property)
        {
            property.serializedObject.ApplyModifiedProperties();
            var target = property.serializedObject.targetObject;
            var path = property.propertyPath;
            var oldValue = property.stringValue;
            var menu = new GenericMenu();
            var count = 0;
            foreach (var field in typeof(GamePages).GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                if (!typeof(EUIPageDef).IsAssignableFrom(field.FieldType)) continue;
                if (field.GetValue(null) is not EUIPageDef page) continue;
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(page.PrefabPath);
                var binding = prefab ? prefab.GetComponent<EUIBinding>() : null;
                var label = binding && !string.IsNullOrWhiteSpace(binding.UIDescription)
                    ? binding.UIDescription + " · " + field.Name : field.Name;
                menu.AddItem(new GUIContent(label.Replace('/', '／')), page.PrefabPath == oldValue,
                    () => SetValue(target, path, page.PrefabPath, oldValue, page));
                count++;
            }
            if (count == 0) menu.AddDisabledItem(new GUIContent("GamePages 中没有页面定义"));
            menu.ShowAsContext();
        }

        internal static void ShowControls(SerializedProperty property)
        {
            property.serializedObject.ApplyModifiedProperties();
            var target = property.serializedObject.targetObject;
            var path = property.propertyPath;
            var oldValue = property.stringValue;
            var parentPath = path.Substring(0, path.LastIndexOf('.'));
            var pagePath = property.serializedObject.FindProperty(parentPath + ".pagePath")?.stringValue;
            var prefab = string.IsNullOrEmpty(pagePath) ? null : AssetDatabase.LoadAssetAtPath<GameObject>(pagePath);
            var menu = new GenericMenu();
            if (!prefab) menu.AddDisabledItem(new GUIContent("先选择可加载的页面 Prefab"));
            else
            {
                menu.AddItem(new GUIContent("整页 / 任意节点（空）"), string.IsNullOrEmpty(oldValue), () => SetValue(target, path, "", oldValue));
                foreach (var node in prefab.GetComponentsInChildren<RectTransform>(true))
                {
                    if (node == prefab.transform) continue;
                    var name = node.name;
                    // 运行器只按名称递归查找；不伪造其尚不支持的层级路径。
                    var hierarchy = AnimationUtility.CalculateTransformPath(node, prefab.transform);
                    menu.AddItem(new GUIContent(hierarchy), name == oldValue, () => SetValue(target, path, name, oldValue));
                }
            }
            menu.ShowAsContext();
        }

        #endregion
    }
}
