// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 框架页面逻辑（生成区文件，框架所有）
/*=============================================================
 * author       : DESKTOP-5SRUU55
 * prefab name  : EUIBackgroundPanel
 * page name    : EUIBackgroundPage
 * create date  : 2026/8/28 12:20:48
 * 本文件为框架生成（混合文件）：
 *   [EmberManaged] 块内 = 框架所有（生命周期 override，刷新时整块替换，勿改）；
 *   块外 = 用户级生命周期（XxxUser 方法），用户只改这里，永不触碰
 ==============================================================*/
using System.Collections;

namespace Game.UI
{
    public partial class EUIBackgroundPage
    {
        // ── 框架生命周期（块内框架所有；每个 override 末尾调用对应的用户级钩子）──
        // [EmberManaged:begin Lifecycle]
        public override void OnInit()
        {
            base.OnInit();
            OnInitUser();
        }

        public override void OnOpen(object param)
        {
            base.OnOpen(param);
            OnOpenUser(param);
        }

        public override void OnShow()
        {
            base.OnShow();
            OnShowUser();
        }

        public override void OnHide()
        {
            base.OnHide();
            OnHideUser();
        }

        public override void OnClose()
        {
            base.OnClose();
            OnCloseUser();
        }

        public override void OnDispose()
        {
            base.OnDispose();
            OnDisposeUser();
        }
        // [EmberManaged:end]

        // ── 用户级生命周期（块外用户区，永不触碰）──

        /// <summary>用户初始化钩子：框架 OnInit 结束时调用。</summary>
        private void OnInitUser()
        {
            // 在此初始化业务数据和事件绑定
        }

        /// <summary>用户打开钩子：框架 OnOpen 结束时调用。</summary>
        private void OnOpenUser(object param)
        {
            // 页面被打开，处理传入参数
        }

        /// <summary>用户显示钩子：框架 OnShow 结束时调用。</summary>
        private void OnShowUser()
        {
            // 页面变为可见
        }

        /// <summary>用户隐藏钩子：框架 OnHide 结束时调用。</summary>
        private void OnHideUser()
        {
            // 页面被隐藏
        }

        /// <summary>用户关闭钩子：框架 OnClose 结束时调用。</summary>
        private void OnCloseUser()
        {
            // 页面被关闭
        }

        /// <summary>用户释放钩子：框架 OnDispose 结束时调用。</summary>
        private void OnDisposeUser()
        {
            // 清理事件与引用
        }
    }
}
