// Copyright (c) 2026 Ember Unity Framework. All rights reserved.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ember.Table.Editor
{
    public sealed class EmberTableArtifactContent
    {
        public string AssetPath { get; }
        public byte[] Bytes { get; }

        public EmberTableArtifactContent(string assetPath, byte[] bytes)
        {
            AssetPath = assetPath?.Replace('\\', '/');
            Bytes = bytes == null ? Array.Empty<byte>() : (byte[])bytes.Clone();
        }

        /// <summary>C# 文本带 UTF-8 BOM，与脚本导入器保持一致；其他文本保持无 BOM。</summary>
        public static EmberTableArtifactContent Text(string assetPath, string content)
        {
            var encoding = new UTF8Encoding(false);
            byte[] bytes = encoding.GetBytes(content);
            if (assetPath != null && assetPath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
                && !content.StartsWith("\uFEFF", StringComparison.Ordinal))
            {
                // GetBytes 不包含编码前导；显式加一次 BOM，避免导入后字节变化。
                byte[] preamble = new UTF8Encoding(true).GetPreamble();
                var scriptBytes = new byte[preamble.Length + bytes.Length];
                Buffer.BlockCopy(preamble, 0, scriptBytes, 0, preamble.Length);
                Buffer.BlockCopy(bytes, 0, scriptBytes, preamble.Length, bytes.Length);
                bytes = scriptBytes;
            }
            return new EmberTableArtifactContent(assetPath, bytes);
        }
    }

    /// <summary>生成逐字段强类型 Binding 与项目 GameTables Catalog；不生成用户 Row。</summary>
    public static class EmberTableCodeGenerator
    {
        public const string GENERATED_MARKER = "// Generated by Ember Table. DO NOT EDIT.";
        public const string GENERATED_ROOT = "Assets/Game/Table/Generated";
        public const string CATALOG_PATH = GENERATED_ROOT + "/GameTables.Catalog.g.cs";

        public static IReadOnlyList<EmberTableArtifactContent> Generate(
            IReadOnlyList<EmberTableValidatedData> tables)
        {
            var artifacts = new List<EmberTableArtifactContent>();
            var classNames = new Dictionary<EmberTableValidatedData, string>();
            for (int i = 0; i < tables.Count; i++)
            {
                EmberTableValidatedData table = tables[i];
                string className = SanitizeIdentifier(table.Schema.RowType.FullName) + "TableBinding";
                classNames.Add(table, className);
                artifacts.Add(EmberTableArtifactContent.Text(
                    GENERATED_ROOT + "/" + className + ".TableBinding.g.cs",
                    GenerateBinding(table, className)));
            }
            artifacts.Add(EmberTableArtifactContent.Text(CATALOG_PATH, GenerateCatalog(tables, classNames)));
            return artifacts;
        }

        private static string GenerateBinding(EmberTableValidatedData table, string className)
        {
            EmberTableSchema schema = table.Schema;
            string rowType = CSharpTypeName(schema.RowType);
            var builder = new StringBuilder();
            builder.AppendLine(GENERATED_MARKER);
            builder.AppendLine();
            builder.AppendLine("namespace Game.Table.Generated");
            builder.AppendLine("{");
            builder.Append("    public sealed class ").Append(className)
                .Append(" : global::Ember.Table.EmberTableBinding<").Append(rowType).AppendLine(">");
            builder.AppendLine("    {");
            builder.Append("        public ").Append(className).AppendLine("()")
                .Append("            : base(\"").Append(EscapeString(schema.TableId)).Append("\", \"")
                .Append(EscapeString(schema.RowTypeId)).Append("\", \"")
                .Append(EscapeString(table.Definition.GetLogicalResourcePath())).Append("\", \"")
                .Append(schema.SchemaHash).AppendLine("\")")
                .AppendLine("        {")
                .AppendLine("        }")
                .AppendLine();
            builder.Append("        protected override ").Append(rowType)
                .AppendLine(" ReadRow(global::Ember.Table.EmberTableBinaryReader reader)")
                .AppendLine("        {");

            var locals = new Dictionary<EmberTableColumnSchema, string>();
            for (int i = 0; i < schema.Columns.Count; i++)
            {
                EmberTableColumnSchema column = schema.Columns[i];
                string local = "value" + i;
                locals.Add(column, local);
                builder.Append("            ").Append(CSharpTypeName(column.ValueType)).Append(' ')
                    .Append(local).Append(" = ").Append(ReadExpression(column)).AppendLine(";");
            }

            builder.Append("            return new ").Append(rowType).Append('(');
            for (int i = 0; i < schema.ConstructorColumns.Count; i++)
            {
                if (i > 0) builder.Append(", ");
                builder.Append(locals[schema.ConstructorColumns[i]]);
            }
            builder.AppendLine(");");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.Append("        protected override string GetPrimaryKey(").Append(rowType).AppendLine(" row)")
                .AppendLine("        {")
                .Append("            return row.").Append(EscapeIdentifier(schema.PrimaryKey.MemberName)).AppendLine(";")
                .AppendLine("        }");

            if (table.Definition.SecondaryIndexes.Count > 0)
            {
                builder.AppendLine();
                builder.Append("        protected override void BuildSecondaryIndexes(global::Ember.Table.EmberTable<")
                    .Append(rowType).AppendLine("> table)")
                    .AppendLine("        {");
                for (int i = 0; i < table.Definition.SecondaryIndexes.Count; i++)
                {
                    EmberTableSecondaryIndexDefinition index = table.Definition.SecondaryIndexes[i];
                    EmberTableColumnSchema column = schema.Columns.First(item =>
                        string.Equals(item.ColumnName, index.ColumnName, StringComparison.Ordinal));
                    builder.Append("            AddSecondaryIndex<").Append(CSharpTypeName(column.ValueType))
                        .Append(">(table, \"").Append(EscapeString(index.Name)).Append("\", row => row.")
                        .Append(EscapeIdentifier(column.MemberName)).Append(", ")
                        .Append(index.Unique ? "true" : "false").AppendLine(");");
                }
                builder.AppendLine("        }");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string GenerateCatalog(
            IReadOnlyList<EmberTableValidatedData> tables,
            IReadOnlyDictionary<EmberTableValidatedData, string> classNames)
        {
            var ordered = tables.OrderBy(item => item.Schema.TableId, StringComparer.Ordinal).ToArray();
            var builder = new StringBuilder();
            builder.AppendLine(GENERATED_MARKER);
            builder.AppendLine();
            builder.AppendLine("namespace Game.Table.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class GameTables");
            builder.AppendLine("    {");
            builder.AppendLine("        [global::Ember.Basic.HasGC]");
            builder.AppendLine("        public static global::Ember.Table.IEmberTableCatalog CreateCatalog()");
            builder.AppendLine("        {");
            builder.AppendLine("            return new global::Ember.Table.EmberTableCatalog(");
            builder.AppendLine("                new global::Ember.Table.EmberTableCatalogEntry[]");
            builder.AppendLine("                {");
            for (int i = 0; i < ordered.Length; i++)
            {
                EmberTableValidatedData table = ordered[i];
                builder.Append("                    new global::Ember.Table.EmberTableCatalogEntry(new ")
                    .Append(classNames[table]).Append("(), ")
                    .Append(table.Definition.Required ? "true" : "false").Append(", ")
                    .Append(table.Definition.MaxFileBytes).Append(", ")
                    .Append(table.Definition.MaxRows).Append(", ")
                    .Append(table.Definition.MaxStringBytes).AppendLine("),");
            }
            builder.AppendLine("                });");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string ReadExpression(EmberTableColumnSchema column)
        {
            string core = ReadNonNullableExpression(column.StorageType);
            if (column.IsNullable)
                return "reader.ReadNullableMarker() ? (" + CSharpTypeName(column.ValueType) + ")(" + core + ") : null";
            return core;
        }

        private static string ReadNonNullableExpression(Type type)
        {
            if (type == typeof(string)) return "reader.ReadString()";
            if (type == typeof(bool)) return "reader.ReadBoolean()";
            if (type == typeof(sbyte)) return "reader.ReadSByte()";
            if (type == typeof(byte)) return "reader.ReadByte()";
            if (type == typeof(short)) return "reader.ReadInt16()";
            if (type == typeof(ushort)) return "reader.ReadUInt16()";
            if (type == typeof(int)) return "reader.ReadInt32()";
            if (type == typeof(uint)) return "reader.ReadUInt32()";
            if (type == typeof(long)) return "reader.ReadInt64()";
            if (type == typeof(ulong)) return "reader.ReadUInt64()";
            if (type == typeof(float)) return "reader.ReadSingle()";
            if (type == typeof(double)) return "reader.ReadDouble()";
            if (type == typeof(decimal)) return "reader.ReadDecimal()";
            if (type.IsEnum)
                return "(" + CSharpTypeName(type) + ")" + ReadNonNullableExpression(Enum.GetUnderlyingType(type));
            throw new NotSupportedException(type.FullName);
        }

        private static string CSharpTypeName(Type type)
        {
            Type nullable = Nullable.GetUnderlyingType(type);
            if (nullable != null) return CSharpTypeName(nullable) + "?";
            if (type == typeof(string)) return "string";
            if (type == typeof(bool)) return "bool";
            if (type == typeof(sbyte)) return "sbyte";
            if (type == typeof(byte)) return "byte";
            if (type == typeof(short)) return "short";
            if (type == typeof(ushort)) return "ushort";
            if (type == typeof(int)) return "int";
            if (type == typeof(uint)) return "uint";
            if (type == typeof(long)) return "long";
            if (type == typeof(ulong)) return "ulong";
            if (type == typeof(float)) return "float";
            if (type == typeof(double)) return "double";
            if (type == typeof(decimal)) return "decimal";
            return "global::" + type.FullName.Replace('+', '.');
        }

        private static string EscapeIdentifier(string value)
        {
            return "@" + value;
        }

        private static string EscapeString(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n");
        }

        private static string SanitizeIdentifier(string value)
        {
            var builder = new StringBuilder(value?.Length ?? 8);
            string input = string.IsNullOrEmpty(value) ? "Row" : value;
            for (int i = 0; i < input.Length; i++)
            {
                char character = input[i];
                builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
            }
            if (builder.Length == 0 || char.IsDigit(builder[0])) builder.Insert(0, '_');
            return builder.ToString();
        }
    }
}
