// Copyright (c) 2026 Ember Unity Framework. All rights reserved.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

using UnityEditor;
using UnityEngine;

namespace Ember.Table.Editor
{
    /// <summary>
    /// 在当前项目 Assets 中创建模板应包含的薄 Table Module 接线。
    /// 已存在的用户扩展文件永不覆盖，正式 Catalog 仍由全量流水线生成。
    /// </summary>
    public static class EmberTableProjectScaffold
    {
        public const string MODULE_PATH = "Assets/Game/Module/Table/GameTableModule.cs";
        public const string USER_PATH = "Assets/Game/Module/Table/GameTableModule.User.cs";

        private const string MODULE_MARKER =
            "// Generated by Ember Setup v0.6.0 (framework v0.12.0) — 框架演示代码（全文件框架所有）";

        private static readonly KeyValuePair<string, string>[] SupplementalFiles =
        {
            new KeyValuePair<string, string>("Assets/Game/Table/README.md", ProjectReadme),
            new KeyValuePair<string, string>("Assets/Game/Table/Rows/README.md", "Put immutable project Table Row types in this directory.\n"),
            new KeyValuePair<string, string>("Assets/Game/Table/Definitions/README.md", "Put project EmberTableDefinition assets in this directory.\n"),
            new KeyValuePair<string, string>("Assets/GameResource/TableSources/README.md", "Put project .etable.csv and .etable.tsv authoring sources in this directory.\n"),
            new KeyValuePair<string, string>("Assets/GameResource/Resources/Config/Tables/README.md", "Generator-owned ETBL V1 binary output lives in this directory.\n"),
        };

        public static bool TryCreate(
            out string summary,
            out IReadOnlyList<EmberTableDiagnostic> diagnostics)
        {
            var resultDiagnostics = new List<EmberTableDiagnostic>();
            diagnostics = resultDiagnostics.AsReadOnly();
            summary = null;

            byte[] moduleBytes = Utf8(ModuleSource);
            string moduleFullPath = ToFullPath(MODULE_PATH);
            if (File.Exists(moduleFullPath) && !BytesEqual(File.ReadAllBytes(moduleFullPath), moduleBytes))
            {
                resultDiagnostics.Add(new EmberTableDiagnostic(
                    EmberTableDiagnosticSeverity.Error,
                    EmberTableErrorCode.UserFileProtected,
                    "GameTableModule.cs already exists and differs from the v0.12.0 scaffold; it was not overwritten.",
                    filePath: MODULE_PATH));
                summary = "项目接线未写入：现有 Module 需要人工合并。";
                return false;
            }

            EmberTablePipelineResult pipeline = EmberTablePipeline.BakeAndGenerateAll();
            for (int i = 0; i < pipeline.Diagnostics.Count; i++) resultDiagnostics.Add(pipeline.Diagnostics[i]);
            if (!pipeline.Succeeded)
            {
                summary = "项目接线未写入：请先修复全量校验或产物提交错误。";
                return false;
            }

            var created = new List<string>();
            try
            {
                AssetDatabase.DisallowAutoRefresh();
                try
                {
                    if (!File.Exists(moduleFullPath))
                    {
                        WriteNewFile(moduleFullPath, moduleBytes);
                        created.Add(moduleFullPath);
                    }

                    string userFullPath = ToFullPath(USER_PATH);
                    if (!File.Exists(userFullPath))
                    {
                        WriteNewFile(userFullPath, Utf8(UserSource));
                        created.Add(userFullPath);
                    }

                    for (int i = 0; i < SupplementalFiles.Length; i++)
                    {
                        string fullPath = ToFullPath(SupplementalFiles[i].Key);
                        if (File.Exists(fullPath)) continue;
                        WriteNewFile(fullPath, Utf8(SupplementalFiles[i].Value));
                        created.Add(fullPath);
                    }
                }
                catch
                {
                    for (int i = 0; i < created.Count; i++)
                        if (File.Exists(created[i])) File.Delete(created[i]);
                    throw;
                }
                finally
                {
                    AssetDatabase.AllowAutoRefresh();
                }

                AssetDatabase.Refresh();
                summary = created.Count == 0
                    ? "项目 Table 接线已存在；Catalog 与二进制产物已重新核对。"
                    : $"已创建 {created.Count} 个项目接线文件，并生成当前 Catalog/二进制产物。";
                return true;
            }
            catch (Exception ex)
            {
                resultDiagnostics.Add(new EmberTableDiagnostic(
                    EmberTableDiagnosticSeverity.Error,
                    EmberTableErrorCode.ArtifactCommitFailed,
                    "Project Table scaffold was rolled back: " + ex.Message));
                summary = "项目接线写入失败；本轮新增接线文件已回滚。";
                return false;
            }
        }

        private static void WriteNewFile(string fullPath, byte[] bytes)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
            string temporary = fullPath + ".embertable." + Guid.NewGuid().ToString("N") + ".tmp";
            try
            {
                File.WriteAllBytes(temporary, bytes);
                File.Move(temporary, fullPath);
            }
            finally
            {
                if (File.Exists(temporary)) File.Delete(temporary);
            }
        }

        private static byte[] Utf8(string value)
        {
            return new UTF8Encoding(false).GetBytes(value.Replace("\r\n", "\n"));
        }

        private static bool BytesEqual(byte[] left, byte[] right)
        {
            if (left == null || right == null || left.Length != right.Length) return false;
            for (int i = 0; i < left.Length; i++) if (left[i] != right[i]) return false;
            return true;
        }

        private static string ToFullPath(string assetPath)
        {
            string projectRoot = Directory.GetParent(Application.dataPath).FullName;
            string fullPath = Path.GetFullPath(Path.Combine(
                projectRoot,
                assetPath.Replace('/', Path.DirectorySeparatorChar)));
            string root = projectRoot.TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
            if (!fullPath.StartsWith(root, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("Project scaffold path escaped the project root.");
            return fullPath;
        }

        private static string ModuleSource => MODULE_MARKER + @"

using Ember.Core;
using Ember.Table;
using Ember.Table.Integration;

using Game.Table.Generated;

namespace Game.Module
{
    /// <summary>项目级 Resource → Table Engine 薄接线；默认关闭，按产品需要启用。</summary>
    [EmberModule(ModulePhase.Global, Enabled = false)]
    public sealed partial class GameTableModule : EmberTableModuleBase<GameTableModule>
    {
        protected override IEmberTableCatalog CreateTableCatalog()
        {
            return GameTables.CreateCatalog();
        }

        protected override void OnTableModuleInitialized()
        {
            OnGameTableModuleInitialized();
        }

        protected override void OnTableModuleDestroying()
        {
            OnGameTableModuleDestroying();
        }

        protected override void ResetTableModuleData()
        {
            OnResetGameTableModuleData();
        }

        partial void OnGameTableModuleInitialized();
        partial void OnGameTableModuleDestroying();
        partial void OnResetGameTableModuleData();
    }
}
";

        private static string UserSource => @"// Project-owned Table Module extensions. This file is never generator-owned.

namespace Game.Module
{
    public sealed partial class GameTableModule
    {
    }
}
";

        private const string ProjectReadme = @"# Project tables

1. Put immutable Row types in `Rows` and mark them with `EmberTable`, `EmberTableKey`, column metadata and one `EmberTableConstructor`.
2. Put `.etable.csv` or `.etable.tsv` sources in `Assets/GameResource/TableSources`.
3. Create `EmberTableDefinition` assets in `Definitions`, then use `Ember/配置表中心` to validate, preview and bake all tables.
4. Enable `GameTableModule` only after the project needs tables. Gameplay code checks `IsReady` and normally consumes a project-owned domain adapter.

Minimal Row shape:

```csharp
[EmberTable(""sample"")]
public sealed class SampleRow
{
    [EmberTableKey, EmberTableColumn(""id"")]
    public string Id { get; }

    [EmberTableConstructor]
    public SampleRow(string id) { Id = id; }
}
```

The generated Catalog/Binding files and `.bytes` files are generator-owned. Do not edit them by hand.
";
    }
}
