// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 框架主菜单页面逻辑（生成区文件，框架所有）
/*=============================================================
 * author       : DESKTOP-5SRUU55
 * prefab name  : EUIMainPanel
 * page name    : EUIMainPage
 * 本文件为框架生成（混合文件）：
 *   [EmberManaged] 块内 = 框架所有（生命周期 override，刷新时整块替换，勿改）；
 *   块外 = 用户级生命周期（XxxUser 方法），用户只改这里，永不触碰
 ==============================================================*/
using Ember.Basic;
using Ember.Core;
using Ember.UI;
using System;

namespace Game.UI
{
    public partial class EUIMainPage
    {
        // ── 框架生命周期（块内框架所有；每个 override 末尾调用对应的用户级钩子）──
        // [EmberManaged:begin Lifecycle]
        private const string TAG = LogTags.Game + "." + nameof(EUIMainPage);

        public override void OnInit()
        {
            base.OnInit();

            Btn_Start.onClick.AddListener(() =>
                GameLauncher.Instance.Fsm.TransitionTo<GameplayState>());

            Btn_Settings.onClick.AddListener(() =>
                GameLauncher.Instance.Fsm.TransitionTo<SettingsState>(SettingsContext.Main));

            OnInitUser();
        }

        public override void OnOpen(object param)
        {
            base.OnOpen(param);
            OnOpenUser(param);
        }

        public override void OnShow()
        {
            base.OnShow();
            OnShowUser();
        }

        public override void OnPause()
        {
            base.OnPause();
            EmberDebug.Log(TAG, "EUIMainPage 被遮挡");
        }

        public override void OnResume()
        {
            base.OnResume();
            EmberDebug.Log(TAG, "EUIMainPage 恢复可见");
        }

        public override void OnHide()
        {
            base.OnHide();
            OnHideUser();
        }

        public override void OnClose()
        {
            base.OnClose();
            OnCloseUser();
        }

        public override void OnDispose()
        {
            Btn_Start.onClick.RemoveAllListeners();
            Btn_Settings.onClick.RemoveAllListeners();
            base.OnDispose();
            OnDisposeUser();
        }
        // [EmberManaged:end]

        // ── 用户级生命周期（块外用户区，永不触碰）──

        /// <summary>用户初始化钩子：框架 OnInit 结束时调用。</summary>
        private void OnInitUser()
        {
            Btn_Start.onClick.RemoveAllListeners();
            Btn_Start.onClick.AddListener(() =>
            {
                if (NovelSaveUI.IsLoading || NovelSaveUI.Module?.IsBusy == true) return;
                NovelSaveUI.StartNewGame();
            });
            NovelContinue.onClick.AddListener(NovelSaveUI.Continue); NovelLoad.onClick.AddListener(NovelSaveUI.Open);
            NovelQuit.onClick.AddListener(QuitGame);
            // 主界面图片同样按当前小说套皮肤；与阅读页共用同一套解析（NarrativeLibrarySO.Current）。
            Game.Narrative.NovelSkin.Apply(this, "EUIMainPanel");
            // 标题是运行期写入的剧情名，订阅全局语言变更后自己重刷（TMPEx 的 Key 覆盖不到它）。
            _languageSubscription = EmberEventBus.Subscribe<string>(EmberBroadcastEvent.LanguageChanged, RefreshNovelTitle);
        }
        private void QuitGame()
        {
            if (NovelSaveUI.IsLoading || _novelSave?.IsBusy == true) return;
            GameLauncher.Instance.Quit();
        }
        private Game.NovelSave.NovelSaveModule _novelSave;
        private IDisposable _languageSubscription;

        /// <summary>
        /// 主界面标题显示的是当前小说的显示名（`story.《剧情 ID》` 表项），不是界面静态文案，
        /// 所以必须自己跟着语言重刷：TMPEx 的 Key 覆盖不到它。
        /// <para>标题控件上原本挂的 `ui.main.Title` Key 已移除——运行期接管的文本不能同时挂 Key，
        /// 否则每次切语言都会被表里的界面标题顶掉。</para>
        /// </summary>
        private void RefreshNovelTitle(string language = null)
        {
            var library = UnityEngine.Resources.Load<Game.Narrative.NarrativeLibrarySO>(Game.Narrative.NarrativeLibrarySO.RESOURCE_PATH);
            string title = library && library.Current ? library.Current.LocalizedDisplayName
                : Game.Narrative.NovelLocalization.Runtime("ui.main.Title", "视觉小说");
            if (NovelTitle is Ember.UIExtension.TMPEx localized) localized.SetSource(title);
            else NovelTitle.text = title;
        }
        private void RefreshNovelSave()
        {
            NovelMessage.text = _novelSave?.Message ?? "";
            bool busy = NovelSaveUI.IsLoading || _novelSave?.IsBusy == true;
            // 两个入口分工不同，都要保留：
            // 「继续游戏」直接续读最新进度（含自动槽），只有存在存档时才出现；
            // 「读取存档」打开槽位页让玩家主动挑档，因此只在存在手动槽（0–5）时才出现。
            bool hasAny = false, hasManual = false;
            if (_novelSave != null)
                foreach (var slot in _novelSave.Store.Slots)
                { hasAny = true; if (slot.Slot >= 0 && slot.Slot < 6) hasManual = true; }
            NovelContinue.gameObject.SetActive(hasAny);
            NovelLoad.gameObject.SetActive(hasManual);
            Btn_Start.interactable = !busy; Btn_Settings.interactable = !busy; NovelQuit.interactable = !busy;
            NovelContinue.interactable = _novelSave != null && !busy && _novelSave.Store.Latest >= 0;
            NovelLoad.interactable = _novelSave != null && !busy;
        }

        /// <summary>用户打开钩子：框架 OnOpen 结束时调用。</summary>
        private void OnOpenUser(object param)
        {
            RefreshNovelTitle();
            _novelSave = NovelSaveUI.Module;
            if (_novelSave != null) _novelSave.Changed += RefreshNovelSave;
            RefreshNovelSave();
        }

        /// <summary>用户显示钩子：框架 OnShow 结束时调用。</summary>
        private void OnShowUser()
        {
            RefreshNovelSave();
        }

        /// <summary>用户隐藏钩子：框架 OnHide 结束时调用。</summary>
        private void OnHideUser()
        {
            // 页面被隐藏
        }

        /// <summary>用户关闭钩子：框架 OnClose 结束时调用。</summary>
        private void OnCloseUser()
        {
            if (_novelSave != null) _novelSave.Changed -= RefreshNovelSave; _novelSave = null;
        }

        /// <summary>用户释放钩子：框架 OnDispose 结束时调用。</summary>
        private void OnDisposeUser()
        {
            _languageSubscription?.Dispose(); _languageSubscription = null;
            OnCloseUser(); NovelContinue.onClick.RemoveListener(NovelSaveUI.Continue); NovelLoad.onClick.RemoveListener(NovelSaveUI.Open);
            NovelQuit.onClick.RemoveListener(QuitGame);
        }
    }
}
