// Copyright (c) 2026 Ember Unity Framework. All rights reserved.
// Package: com.ember.uiextension

using System.IO;
using System.Text;

using Ember.Basic;

using UnityEditor;

using UnityEngine;

namespace Ember.UIExtension.Editor
{
    /// <summary>
    /// UI 绑定代码生成器。
    /// 读取场景/预制体中的 <see cref="EmberUIBinding"/> 组件，
    /// 自动生成 partial class 中的控件字段和 OnBind() 方法。
    ///
    /// <para>生成规范：</para>
    /// <list type="bullet">
    ///   <item>.bindings.cs —— 每次生成都覆盖，包含字段声明 + OnBind() 方法体</item>
    ///   <item>.cs —— 仅首次生成，包含 partial class 骨架（OnInit/OnOpen/OnClose 等钩子模板），之后不覆盖</item>
    /// </list>
    /// </summary>
    public static class EmberUIBindingGenerator
    {
        private const string TAG = LogTags.EmberUI;
        private const string MenuPath = "Ember/UI/Generate All Bindings";
        private const string BindingsSuffix = ".bindings.cs";

        #region 外部方法

        /// <summary>
        /// 菜单：扫描当前场景中所有 EmberUIBinding，批量生成绑定代码。
        /// </summary>
        [MenuItem(MenuPath)]
        public static void GenerateAllBindings()
        {
            var bindings = Object.FindObjectsByType<EmberUIBinding>();
            if (bindings.Length == 0)
            {
                EmberDebug.LogWarning(TAG, "当前场景中未找到 EmberUIBinding 组件。");
                return;
            }

            int count = 0;
            foreach (var binding in bindings)
            {
                if (GenerateSingle(binding))
                    count++;
            }

            AssetDatabase.Refresh();
            EmberDebug.Log(TAG, $"绑定代码生成完成：{count}/{bindings.Length}");
        }

        /// <summary>
        /// 为单个 EmberUIBinding 生成绑定代码。
        /// </summary>
        /// <param name="binding">绑定组件</param>
        /// <returns>是否成功生成</returns>
        public static bool GenerateSingle(EmberUIBinding binding)
        {
            if (binding == null) return false;

            if (string.IsNullOrEmpty(binding.ClassName))
            {
                EmberDebug.LogWarning(TAG, $"跳过 {binding.name}：ClassName 未设置。");
                return false;
            }

            // 确保输出目录存在
            var dir = Path.Combine(Application.dataPath, binding.OutputDirectory);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            // 1. 生成 .bindings.cs（每次覆盖）
            GenerateBindingsFile(binding, dir);

            // 2. 生成 .cs 骨架（仅首次）
            GenerateSkeletonFile(binding, dir);

            EmberDebug.Log(TAG, $"已生成: {binding.ClassName}.bindings.cs → {binding.OutputDirectory}/");
            return true;
        }

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        /// <summary>生成 .bindings.cs 文件（字段 + OnBind）</summary>
        private static void GenerateBindingsFile(EmberUIBinding binding, string dir)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by EmberUIBindingGenerator. Do not edit.");
            sb.AppendLine("// Source: " + GetSourcePath(binding));
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();

            var ns = binding.NamespaceName;
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            var baseClass = string.IsNullOrEmpty(binding.BaseClassName)
                ? "Ember.UI.EmberPage"
                : binding.BaseClassName;
            sb.AppendLine($"    public partial class {binding.ClassName} : {baseClass}");
            sb.AppendLine("    {");

            // 字段
            if (binding.Bindings != null && binding.Bindings.Length > 0)
            {
                foreach (var entry in binding.Bindings)
                {
                    if (string.IsNullOrEmpty(entry.Name)) continue;
                    var typeName = GetCSharpTypeName(entry);
                    sb.AppendLine($"        private {typeName} _{entry.Name};");
                }
            }

            sb.AppendLine();

            // OnBind 方法
            sb.AppendLine("        public override void OnBind()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnBind();");
            sb.AppendLine();

            if (binding.Bindings != null && binding.Bindings.Length > 0)
            {
                foreach (var entry in binding.Bindings)
                {
                    if (string.IsNullOrEmpty(entry.Name)) continue;
                    var typeName = GetCSharpTypeName(entry);
                    sb.AppendLine($"            _{entry.Name} = GetBinding<{typeName}>(\"{entry.Name}\");");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var path = Path.Combine(dir, binding.ClassName + BindingsSuffix);
            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
        }

        /// <summary>生成 .cs 骨架文件（仅首次，含生命周期钩子模板）</summary>
        private static void GenerateSkeletonFile(EmberUIBinding binding, string dir)
        {
            var path = Path.Combine(dir, binding.ClassName + ".cs");
            if (File.Exists(path)) return; // 已存在，不覆盖

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated skeleton by EmberUIBindingGenerator.");
            sb.AppendLine("// You can edit this file freely — it will NOT be overwritten.");
            sb.AppendLine();
            sb.AppendLine("using System.Collections;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {binding.NamespaceName}");
            sb.AppendLine("{");

            var baseClass = string.IsNullOrEmpty(binding.BaseClassName)
                ? "Ember.UI.EmberPage"
                : binding.BaseClassName;
            sb.AppendLine($"    public partial class {binding.ClassName}");
            sb.AppendLine("    {");

            sb.AppendLine("        // ── 生命周期钩子 ──");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnInitialize(object args)");
            sb.AppendLine("        {");
            sb.AppendLine("            // 在此处初始化数据：填文字、设图片、注册事件");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override IEnumerator OnShow()");
            sb.AppendLine("        {");
            sb.AppendLine("            // 打开动画（可选）");
            sb.AppendLine("            // yield return YourTween.Play();");
            sb.AppendLine("            yield break;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override IEnumerator OnHide()");
            sb.AppendLine("        {");
            sb.AppendLine("            // 关闭动画（可选）");
            sb.AppendLine("            yield break;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnCleanup()");
            sb.AppendLine("        {");
            sb.AppendLine("            // 清理：注销事件、释放引用");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
        }

        /// <summary>将 WidgetType 映射为 C# 类型名</summary>
        private static string GetCSharpTypeName(EmberUIBinding.BindingEntry entry)
        {
            if (entry.Type == EmberUIBinding.WidgetType.Extension && !string.IsNullOrEmpty(entry.ClassName))
                return entry.ClassName;

            return entry.Type switch
            {
                EmberUIBinding.WidgetType.Component   => "Component",
                EmberUIBinding.WidgetType.Text        => "TMPro.TextMeshProUGUI",
                EmberUIBinding.WidgetType.Image       => "Image",
                EmberUIBinding.WidgetType.RawImage    => "RawImage",
                EmberUIBinding.WidgetType.Button      => "Button",
                EmberUIBinding.WidgetType.Toggle      => "Toggle",
                EmberUIBinding.WidgetType.ToggleGroup => "ToggleGroup",
                EmberUIBinding.WidgetType.InputField  => "TMP_InputField",
                EmberUIBinding.WidgetType.ScrollRect  => "ScrollRect",
                EmberUIBinding.WidgetType.Slider      => "Slider",
                EmberUIBinding.WidgetType.Dropdown    => "TMP_Dropdown",
                _ => "Component",
            };
        }

        /// <summary>获取源 prefab 或场景路径</summary>
        private static string GetSourcePath(EmberUIBinding binding)
        {
            var prefabPath = PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(binding);
            if (!string.IsNullOrEmpty(prefabPath))
                return prefabPath;

            return binding.gameObject.scene.name + "/" + binding.name;
        }

        #endregion
    }
}
