////using System.IO;
////using System.Text;
////using UnityEditor;
////using UnityEngine;
////
////namespace Ember.UIExtension.Editor
////{
////    /// <summary>
////    /// UI 绑定代码生成器 —— 读取场景/预制体中的 <see cref="EmberUIBinding"/> 组件，
////    /// 自动生成 partial class 中的控件引用代码。
////    ///
////    /// 生成的代码包含：
////    /// - 每个绑定控件的私有字段
////    /// - OnBind() 方法，调用 GetBinding&lt;T&gt;() 赋值
////    ///
////    /// TODO: 实现实际的代码生成逻辑
////    /// </summary>
////    public static class EmberUIBindingGenerator
////    {
////        /// <summary>
////        /// 菜单：Ember > UI > Generate Binding Code
////        /// 扫描当前打开场景中所有 EmberUIBinding，为每个页面生成绑定代码。
////        /// </summary>
////        [MenuItem("Ember/UI/Generate Binding Code")]
////        public static void GenerateAllBindings()
////        {
////            var bindings = Object.FindObjectsOfType<EmberUIBinding>();
////            if (bindings.Length == 0)
////            {
////                Debug.LogWarning("[Ember] No EmberUIBinding components found in the current scene.");
////                return;
////            }
////
////            foreach (var binding in bindings)
////            {
////                GenerateBindingCode(binding);
////            }
////
////            AssetDatabase.Refresh();
////            Debug.Log($"[Ember] Binding code generated for {bindings.Length} component(s).");
////        }
////
////        private static void GenerateBindingCode(EmberUIBinding binding)
////        {
////            if (string.IsNullOrEmpty(binding.ClassName))
////            {
////                Debug.LogWarning(
////                    $"[Ember] Skipping {binding.name}: ClassName is not set.");
////                return;
////            }
////
////            var sb = new StringBuilder();
////            sb.AppendLine($"// Auto-generated by EmberUIBindingGenerator. Do not edit manually.");
////            sb.AppendLine();
////            sb.AppendLine($"using UnityEngine;");
////            sb.AppendLine($"using UnityEngine.UI;");
////            sb.AppendLine();
////            sb.AppendLine($"namespace Game.UI");
////            sb.AppendLine($"{{");
////            sb.AppendLine($"    public partial class {binding.ClassName}");
////            sb.AppendLine($"    {{");
////
////            foreach (var entry in binding.Bindings)
////            {
////                if (string.IsNullOrEmpty(entry.Name)) continue;
////                var typeName = GetTypeName(entry.Type);
////                sb.AppendLine($"        private {typeName} _{entry.Name};");
////            }
////
////            sb.AppendLine();
////            sb.AppendLine($"        private void OnBind()");
////            sb.AppendLine($"        {{");
////
////            foreach (var entry in binding.Bindings)
////            {
////                if (string.IsNullOrEmpty(entry.Name)) continue;
////                var typeName = GetTypeName(entry.Type);
////                sb.AppendLine(
////                    $"            _{entry.Name} = GetBindingComponent<{typeName}>(\"{entry.Name}\");");
////            }
////
////            sb.AppendLine($"        }}");
////            sb.AppendLine($"    }}");
////            sb.AppendLine($"}}");
////
////            // 写入 Generated 目录
////            var dir = "Assets/Game/UI/Generated";
////            if (!Directory.Exists(dir))
////                Directory.CreateDirectory(dir);
////
////            var path = Path.Combine(dir, $"{binding.ClassName}.bindings.cs");
////            File.WriteAllText(path, sb.ToString());
////            Debug.Log($"[Ember] Generated: {path}");
////        }
////
////        private static string GetTypeName(EmberUIBinding.WidgetType type)
////        {
////            return type switch
////            {
////                EmberUIBinding.WidgetType.Text       => "Text",
////                EmberUIBinding.WidgetType.Image      => "Image",
////                EmberUIBinding.WidgetType.RawImage   => "RawImage",
////                EmberUIBinding.WidgetType.Button     => "Button",
////                EmberUIBinding.WidgetType.Toggle     => "Toggle",
////                EmberUIBinding.WidgetType.ToggleGroup => "ToggleGroup",
////                EmberUIBinding.WidgetType.InputField  => "InputField",
////                EmberUIBinding.WidgetType.ScrollRect  => "ScrollRect",
////                EmberUIBinding.WidgetType.Slider      => "Slider",
////                EmberUIBinding.WidgetType.Dropdown    => "Dropdown",
////                _                                      => "Component",
////            };
////        }
////    }
////}
