// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 框架 Loading 页逻辑（生成区文件，框架所有）
/*=============================================================
 * author       : DESKTOP-5SRUU55
 * prefab name  : EUILoadingPanel
 * page name    : EUILoadingPage
 * 本文件为框架生成（混合文件）：
 *   [EmberManaged] 块内 = 框架所有（生命周期 override 与框架逻辑，刷新时整块替换，勿改）；
 *   块外 = 用户级生命周期（XxxUser 方法），用户只改这里，永不触碰
 *
 * 进度显示状态管理约定（防止状态残留/首帧闪现）：
 *   打开：OnResetDefault（初始化之前）先「恢复默认」（进度条与数字关闭）→ OnInit/OnShow「按模式重新激活」；
 *   关闭：OnClose 之后 OnResetDefault 再次「恢复默认」。
 *   即：任何显示开关都遵循「先恢复默认，再按参数打开」，绝不依赖上一次运行时的残留状态。
 ==============================================================*/

using Cysharp.Threading.Tasks;

using Ember.Core;
using Ember.Scene;
using Ember.UI;

using UnityEngine;
using UnityEngine.UI;

using TMPro;

namespace Game.UI
{
    public partial class EUILoadingPage
    {
        // ── 框架代码（块内框架所有；生命周期 override 末尾调用对应的用户级钩子）──
        // [EmberManaged:begin Lifecycle]
        #region 内部参数

        private EUILoadingPageSettings _settings;

        // 假进度状态
        private float _fastElapsed;
        private float _tailElapsed;
        private float _displayProgress;
        private bool _inTailPhase;
        private bool _fakeComplete;
        private bool _fadeInDone; // 渐入完成前不开始计时

        #endregion

        // --------------------------------------------------------

        #region 生命周期钩子

        public override void OnInit()
        {
            base.OnInit();
            _settings = CustomSettings as EUILoadingPageSettings;
            NeedUpdate = true;
            // 顶层状态机的快速转场判定必须在 OnShow 之前生效：
            // 拦截器在页面打开完成后才送达 SkipFakeProgress，若等那时，OnShow 已按开关把进度条显示出来了
            if (EmberStateMachine.QuickSceneLoad)
                SkipFakeProgress = true;
            // 只有假进度模式才在 Init 阶段重置进度显示（快速模式不激活进度条/数字，避免闪现）
            if (UseFakeProgress)
                ApplySettings();
            else
                HideProgressVisuals();
            OnInitUser();
        }

        public override void OnOpen(object param)
        {
            base.OnOpen(param);
            OnOpenUser(param);
        }

        public override void OnShow()
        {
            base.OnShow();

            if (UseFakeProgress)
            {
                _fastElapsed = 0f;
                _tailElapsed = 0f;
                _displayProgress = 0f;
                _inTailPhase = false;
                _fakeComplete = false;
                _fadeInDone = false;
                ApplySettings();
            }
            else
            {
                // 快速/无进度显示模式：不跑假进度，隐藏进度条与数字
                HideProgressVisuals();
            }

            EmberEventBus.OnNext(EUIEvents.LoadingFadeInStart);
            OnShowUser();
        }

        public override void OnHide()
        {
            base.OnHide();
            NeedUpdate = false;
            OnHideUser();
        }

        public override void OnClose()
        {
            base.OnClose();
            OnCloseUser();
        }

        public override void OnDispose()
        {
            base.OnDispose();
            OnDisposeUser();
        }

        public override void OnUpdate()
        {
            // 无假进度模式（显式快速转场 / 未勾选任何进度显示 / 无配置）：只隐藏进度显示，
            // 就绪由 IsTransitionReady 的真实加载判定
            if (!UseFakeProgress)
            {
                HideProgressVisuals();
                return;
            }

            // 渐入完成前不开始计时（进度条在此期间不可见）
            if (_fakeComplete || !_fadeInDone) return;

            var sceneMgr = EmberSceneManager.Instance;
            bool realDone = sceneMgr != null && !sceneMgr.IsLoading;

            if (!_inTailPhase)
            {
                // Phase 1: 快充阶段 → 阈值
                _fastElapsed += Time.deltaTime;
                float fastT = Mathf.Clamp01(_fastElapsed / _settings.fastFillDuration);
                _displayProgress = fastT * _settings.fastFillThreshold;

                if (fastT >= 1f)
                {
                    if (realDone)
                    {
                        // 真实加载已完成 → 进入收尾
                        _inTailPhase = true;
                        _tailElapsed = 0f;
                    }
                    else
                    {
                        // 真实加载未完成 → 卡在阈值等待
                        _displayProgress = _settings.fastFillThreshold;
                    }
                }
            }

            if (_inTailPhase)
            {
                // Phase 2: 收尾阶段 → 当前进度平滑到 100%
                _tailElapsed += Time.deltaTime;
                float tailT = Mathf.Clamp01(_tailElapsed / _settings.tailDuration);
                _displayProgress = Mathf.Lerp(_settings.fastFillThreshold, 1f, tailT);

                if (tailT >= 1f)
                {
                    _displayProgress = 1f;
                    _fakeComplete = true;
                }
            }

            SetProgress(_displayProgress);
        }

        public override void OnResetDefault()
        {
            base.OnResetDefault();
            _fastElapsed = 0f;
            _tailElapsed = 0f;
            _displayProgress = 0f;
            _inTailPhase = false;
            _fakeComplete = false;
            SkipFakeProgress = false; // 每次打开默认回到假进度模式，快速转场由业务侧显式开启
            SetProgress(0f);
            // 恢复默认：进度条/数字彻底关闭；打开时由 OnShow 按模式决定是否重新激活，
            // 关闭时保证复用/下次打开从干净状态开始（杜绝任何残留闪现）
            HideProgressVisuals();
            TransitionEffect?.HideAllImmediate();
        }

        #endregion

        // --------------------------------------------------------

        #region 外部方法

        /// <summary>
        /// 手动设置加载进度（0-1），更新进度条和数字。
        /// 如果不手动调用，OnUpdate 通过 timer 驱动假进度 0→1，不依赖真实加载进度。
        /// </summary>
        public void SetProgress(float progress)
        {
            progress = Mathf.Clamp01(progress);

            if (_settings != null)
            {
                if (_settings.useProgressBar && Img_ProgressBar != null)
                {
                    Img_ProgressBar.fillAmount = progress;
                    Img_ProgressBar.gameObject.SetActive(true);
                }
                else if (Img_ProgressBar != null)
                {
                    Img_ProgressBar.gameObject.SetActive(false);
                }

                if (_settings.useProgressNumber && Txt_ProgressNum != null)
                {
                    Txt_ProgressNum.text = $"{(int)(progress * 100)}%";
                    Txt_ProgressNum.gameObject.SetActive(true);
                }
                else if (Txt_ProgressNum != null)
                {
                    Txt_ProgressNum.gameObject.SetActive(false);
                }
            }
        }

        /// <summary>
        /// 展示进度的平滑收尾时长（秒）。
        /// <see cref="EUIManager.TransitionSceneWithLoading"/> 在关闭页面前等待此时长。
        /// 假进度模式下返回 0，事件驱动关闭。
        /// </summary>
        public override float SmoothTailDuration => 0f;

        /// <summary>假进度是否已完成</summary>
        public bool IsFakeComplete => _fakeComplete;

        /// <inheritdoc/>
        public override bool IsTransitionReady
        {
            get
            {
                // 无假进度（快速转场 / 未勾选进度显示 / 无配置）：真实场景加载完成即就绪
                if (!UseFakeProgress)
                {
                    var sceneMgr = EmberSceneManager.Instance;
                    return sceneMgr == null || !sceneMgr.IsLoading;
                }
                return _fakeComplete;
            }
        }

        /// <summary>
        /// 是否需要假进度：未显式跳过，且进度显示（进度条/数字）至少勾选其一，且配置存在。
        /// 快速转场（SkipFakeProgress）或未勾选任何进度显示时自动回退真实加载模式。
        /// </summary>
        private bool UseFakeProgress =>
            !SkipFakeProgress
            && _settings != null
            && (_settings.useProgressBar || _settings.useProgressNumber);

        /// <summary>隐藏进度条与进度数字（快速转场模式）</summary>
        private void HideProgressVisuals()
        {
            if (Img_ProgressBar != null)
                Img_ProgressBar.gameObject.SetActive(false);
            if (Txt_ProgressNum != null)
                Txt_ProgressNum.gameObject.SetActive(false);
        }

        /// <summary>
        /// 方块过渡效果（将绑定字段 Component 转换为 IEUITransitionEffect）。
        /// 绑定代码生成器只能产出 Component 类型，这里做接口转换。
        /// </summary>
        private IEUITransitionEffect TransitionEffect => TransitionBlock as IEUITransitionEffect;

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        private void ApplySettings()
        {
            if (_settings == null) return;
            SetProgress(0f);

            // 初始化进度条组透明度（自定义动画接管前先隐藏）
            if (Cg_Progress != null)
                Cg_Progress.alpha = 0f;
        }

        #endregion

        // --------------------------------------------------------

        #region 自定义过渡动画

        /// <summary>
        /// 过渡动画进入阶段（Custom 槽）。方块扫入已由预设槽（EUITransitionBlock）完成，
        /// 这里仅负责进度条组渐显。
        /// </summary>
        public override async UniTask OnCustomEnter()
        {
            if (_settings == null) return;

            // 进度条组渐显
            if (Cg_Progress == null) return;
            var duration = _settings.customEnterDuration;
            if (duration <= 0f) { Cg_Progress.alpha = 1f; return; }

            float elapsed = 0f;
            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                Cg_Progress.alpha = Mathf.Clamp01(elapsed / duration);
                await UniTask.Yield(PlayerLoopTiming.Update);
            }
            Cg_Progress.alpha = 1f;
            _fadeInDone = true;
            EmberEventBus.OnNext(EUIEvents.LoadingFadeInComplete);
        }

        /// <summary>
        /// 过渡动画退出阶段（Custom 槽）。这里仅负责进度条组渐隐；
        /// 方块扫出由预设槽（EUITransitionBlock）在自定义之后播放。
        /// </summary>
        public override async UniTask OnCustomExit()
        {
            if (_settings == null) return;

            var exitDuration = _settings.customExitDuration;
            EmberEventBus.OnNext(EUIEvents.LoadingFadeOutStart, exitDuration);

            // 进度条组渐隐
            if (Cg_Progress != null && exitDuration > 0f)
            {
                float elapsed = 0f;
                var startAlpha = Cg_Progress.alpha;
                while (elapsed < exitDuration)
                {
                    elapsed += Time.deltaTime;
                    Cg_Progress.alpha = Mathf.Lerp(startAlpha, 0f, elapsed / exitDuration);
                    await UniTask.Yield(PlayerLoopTiming.Update);
                }
            }

            if (Cg_Progress != null) Cg_Progress.alpha = 0f;
            EmberEventBus.OnNext(EUIEvents.LoadingFadeOutComplete);
        }

        #endregion
        // [EmberManaged:end]

        // ── 用户级生命周期（块外用户区，永不触碰）──

        /// <summary>用户初始化钩子：框架 OnInit 结束时调用。</summary>
        private void OnInitUser()
        {
            // 在此初始化业务数据和事件绑定
        }

        /// <summary>用户打开钩子：框架 OnOpen 结束时调用。</summary>
        private void OnOpenUser(object param)
        {
            // 页面被打开，处理传入参数
        }

        /// <summary>用户显示钩子：框架 OnShow 结束时调用。</summary>
        private void OnShowUser()
        {
            // 页面变为可见
        }

        /// <summary>用户隐藏钩子：框架 OnHide 结束时调用。</summary>
        private void OnHideUser()
        {
            // 页面被隐藏
        }

        /// <summary>用户关闭钩子：框架 OnClose 结束时调用。</summary>
        private void OnCloseUser()
        {
            // 页面被关闭
        }

        /// <summary>用户释放钩子：框架 OnDispose 结束时调用。</summary>
        private void OnDisposeUser()
        {
            // 清理事件与引用
        }
    }
}
