// Generated by Ember Setup v0.3.0 (framework v0.9.0) — 游戏层 Gameplay 状态（生成区文件，含业务增量）
using Ember.Core;
using Ember.UI;
using Game.UI;

namespace Game.State
{
    /// <summary>
    /// 游戏层 GameplayState 子类 —— override 框架钩子，注入业务逻辑。
    ///
    /// <b>进入玩法 → 打开游戏内 UI：</b>
    /// <see cref="OnGameplayEnter"/> 在场景加载完成后调用，打开 InGameUI。
    ///
    /// <b>退出玩法 → 关闭所有 UI：</b>
    /// <see cref="OnGameplayExit"/> 在离开玩法前调用，清理 UI。
    /// </summary>
    public class GameGameplayState : GameplayState
    {
        // [EmberManaged:begin OnGameplayEnter]
        protected override void OnGameplayEnter(object args)
        // [EmberManaged:end]
        {
            base.OnGameplayEnter(args);
            EUIManager.Instance.ShowMainPage(GamePages.EUIGamePlayPage);
        }

        // [EmberManaged:begin OnGameplayExit]
        protected override void OnGameplayExit()
        // [EmberManaged:end]
        {
            EUIManager.Instance.CloseAllPopups();
            EUIManager.Instance.ClosePageByDef(GamePages.EUIGamePlayPage);
            base.OnGameplayExit();
        }
    }
}
