// Generated by Ember Setup v0.3.0 (framework v0.12.6) — 框架演示代码（全文件框架所有）
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Game.Module.Guide.Editor
{
    /// <summary>引导编辑器的类型映射、步骤操作和只读配置检查。</summary>
    internal static class GuideEditorModel
    {
        #region 内部参数

        internal static readonly string[] EventNames =
            { "无事件", "页面打开", "页面关闭", "UI 按钮点击", "延时结束", "引导遮罩点击", "自定义事件" };
        internal static readonly string[] ExecutorNames =
            { "打开遮罩", "关闭遮罩", "显示小手", "关闭小手", "打开页面", "关闭页面", "延时", "显示提示", "输出日志" };
        internal static readonly string[] ConditionNames =
            { "未设置", "恒真", "恒假", "由指定事件触发", "页面显示状态", "引导已完成", "整数比较", "全部满足（AND）", "任一满足（OR）" };

        #endregion

        // --------------------------------------------------------

        #region 内部方法

        private static void CheckCondition(GuideConditionBase condition, string path, List<string> issues,
            HashSet<GuideConditionBase> visiting)
        {
            if (condition == null) return;
            if (!visiting.Add(condition)) { issues.Add(path + "存在循环条件引用。"); return; }
            if (condition is GuideConditionGroup group)
            {
                if (group.conditions == null || group.conditions.Count == 0)
                    issues.Add(path + "是空条件组：AND 恒真，OR 恒假。");
                if (group.conditions != null)
                    foreach (var child in group.conditions) CheckCondition(child, path + " / 子条件", issues, visiting);
            }
            else if (condition is GuideCondition single)
            {
                if (!Enum.IsDefined(typeof(GuideConditionType), single.conditionType)) issues.Add(path + "的条件类型无效。");
                CheckParameter(single, single.conditionParams, path, issues);
            }
            visiting.Remove(condition);
        }

        private static void CheckItems<T>(List<T> items, string path, List<string> issues)
        {
            if (items == null) return;
            for (var i = 0; i < items.Count; i++)
            {
                var itemPath = path + $" #{i + 1}";
                if (items[i] is GuideEvent e)
                {
                    if (e.eventType == GuideEventType.None || !Enum.IsDefined(typeof(GuideEventType), e.eventType))
                        issues.Add(itemPath + "未选择有效事件。");
                    CheckParameter(e, e.eventParam, itemPath, issues);
                }
                else if (items[i] is GuideExecutor executor)
                {
                    if (!Enum.IsDefined(typeof(GuideExecuteType), executor.executeType)) issues.Add(itemPath + "的执行类型无效。");
                    CheckParameter(executor, executor.executeParam, itemPath, issues);
                }
                else issues.Add(itemPath + "为空。");
            }
        }

        private static void CheckParameter(object owner, object parameter, string path, List<string> issues)
        {
            var type = ParameterType(owner);
            if (type != null && (parameter == null || parameter.GetType() != type))
                issues.Add(path + "缺少参数或参数类型不匹配，请使用“创建/重建参数”。");
            if (parameter is GuideExeParamDelay delay && delay.seconds < 0) issues.Add(path + "的延时不能小于 0。");
            if (parameter is GuideExeParamOpenUI open && string.IsNullOrWhiteSpace(open.prefabPath)) issues.Add(path + "没有设置页面路径。");
            if (parameter is GuideExeParamOpenUI page && page.pageType != Ember.UI.PageType.MainPage
                && page.pageType != Ember.UI.PageType.Popup && page.pageType != Ember.UI.PageType.FullScreenPopup
                && page.pageType != Ember.UI.PageType.TopMost)
                issues.Add(path + "的页面类型未被当前打开页面执行器支持，请使用业务执行器处理。");
            if (parameter is GuideExeParamCloseUI close && string.IsNullOrWhiteSpace(close.prefabPath)) issues.Add(path + "没有设置页面路径。");
            if (parameter is GuideExeParamOpenHand hand && string.IsNullOrWhiteSpace(hand.pagePath)) issues.Add(path + "没有设置小手目标页面，运行时无法定位。");
        }

        #endregion

        // --------------------------------------------------------

        #region 外部方法

        internal static Type ParameterType(object value)
        {
            if (value is GuideEvent e)
                return e.eventType switch
                {
                    GuideEventType.OnPageShown or GuideEventType.OnPageHidden => typeof(GuideEventParamPage),
                    GuideEventType.OnClickUIButton => typeof(GuideEventParamClickUI),
                    GuideEventType.OnCustom => typeof(GuideEventParamCustom),
                    _ => null
                };
            if (value is GuideExecutor executor)
                return executor.executeType switch
                {
                    GuideExecuteType.OpenMask => typeof(GuideExeParamMask),
                    GuideExecuteType.OpenHand => typeof(GuideExeParamOpenHand),
                    GuideExecuteType.OpenUI => typeof(GuideExeParamOpenUI),
                    GuideExecuteType.CloseUI => typeof(GuideExeParamCloseUI),
                    GuideExecuteType.Delay => typeof(GuideExeParamDelay),
                    GuideExecuteType.ShowTips => typeof(GuideExeParamShowTips),
                    GuideExecuteType.Log => typeof(GuideExeParamLog),
                    _ => null
                };
            if (value is GuideCondition condition)
                return condition.conditionType switch
                {
                    GuideConditionType.IsTriggerByEvent => typeof(GuideCondParamIsTriggerByEvent),
                    GuideConditionType.IsUIShowing => typeof(GuideCondParamIsUIShowing),
                    GuideConditionType.IsGuideFinished => typeof(GuideCondParamGuideFinished),
                    GuideConditionType.CompareInt => typeof(GuideCondParamCompareInt),
                    _ => null
                };
            return null;
        }

        internal static GuideConditionBase CreateCondition(int selection)
        {
            if (selection == 0) return null;
            if (selection >= 7)
                return new GuideConditionGroup { logicOperator = selection == 7 ? LogicOperator.And : LogicOperator.Or };
            var condition = new GuideCondition { conditionType = (GuideConditionType)selection };
            var type = ParameterType(condition);
            condition.conditionParams = type == null ? null : Activator.CreateInstance(type);
            return condition;
        }

        internal static bool CanEdit(GuideDefine define)
        {
            if (!define || EditorApplication.isPlayingOrWillChangePlaymode) return false;
            var path = AssetDatabase.GetAssetPath(define);
            return path.StartsWith("Assets/", StringComparison.Ordinal)
                && AssetDatabase.IsOpenForEdit(define);
        }

        internal static void AddStep(GuideDefine define, int copyIndex = -1)
        {
            if (!CanEdit(define)) return;
            GuideDefine clone = null;
            try
            {
                var step = new GuideStepDefine { name = "新步骤" };
                if (copyIndex >= 0)
                {
                    // 克隆整个 SO，让嵌套 SerializeReference 由 Unity 深拷贝，避免副本修改原步骤。
                    clone = UnityEngine.Object.Instantiate(define);
                    step = clone.guideSteps[copyIndex];
                    step.name = (step.name ?? "步骤") + "（副本）";
                }
                Undo.RecordObject(define, copyIndex < 0 ? "添加引导步骤" : "复制引导步骤");
                define.guideSteps ??= new List<GuideStepDefine>();
                define.guideSteps.Insert(copyIndex < 0 ? define.guideSteps.Count : copyIndex + 1, step);
                EditorUtility.SetDirty(define);
            }
            finally
            {
                if (clone) UnityEngine.Object.DestroyImmediate(clone);
            }
        }

        internal static List<string> Validate(GuideDefine define)
        {
            var issues = new List<string>();
            if (!define) return issues;
            var visited = new HashSet<GuideConditionBase>();
            CheckCondition(define.baseSkipAll, "全局跳过", issues, visited);
            if (define.guideSteps == null || define.guideSteps.Count == 0)
                issues.Add("尚未添加步骤。");
            if (define.guideSteps == null) return issues;
            for (var i = 0; i < define.guideSteps.Count; i++)
            {
                var s = define.guideSteps[i];
                var prefix = $"步骤 {i + 1}";
                if (s == null) { issues.Add(prefix + "为空。"); continue; }
                if (string.IsNullOrWhiteSpace(s.name)) issues.Add(prefix + "没有填写用途名称。");
                CheckCondition(s.startConditionsToSkipAll, prefix + " / 跳过引导", issues, visited);
                CheckCondition(s.startConditionsToSkip, prefix + " / 跳过步骤", issues, visited);
                CheckCondition(s.startConditionsToSuccess, prefix + " / 开始条件", issues, visited);
                CheckCondition(s.endConditionsToFinishAll, prefix + " / 完成引导", issues, visited);
                CheckCondition(s.endConditionsToCancelAll, prefix + " / 取消引导", issues, visited);
                CheckCondition(s.endConditionsToCancel, prefix + " / 取消步骤", issues, visited);
                CheckCondition(s.endConditionsToSuccess, prefix + " / 完成条件", issues, visited);
                CheckItems(s.startEvents, prefix + " / 开始事件", issues);
                CheckItems(s.endEvents, prefix + " / 结束事件", issues);
                CheckItems(s.startExecutors, prefix + " / 开始执行器", issues);
                CheckItems(s.endExecutors, prefix + " / 结束执行器", issues);
                if (s.endConditionsToSuccess == null)
                    issues.Add(prefix + "未设置完成条件：进入后会立即完成；需要等待点击或延时时，请配置结束事件和完成条件。");
                if (!s.needUpdate && s.endConditionsToSuccess != null && (s.endEvents == null || s.endEvents.Count == 0))
                    issues.Add(prefix + "设置了完成条件，但没有结束事件且未启用每帧检查，条件变化可能无法推进。");
            }
            return issues;
        }

        #endregion
    }
}
