// Generated by Ember Setup v0.3.0 (framework v0.12.6) — 框架演示代码（全文件框架所有）
using UnityEditor;
using UnityEngine;

namespace Game.Module.Guide.Editor
{
    /// <summary>引导定义 Inspector，与独立窗口共用条件和参数绘制。</summary>
    [CustomEditor(typeof(GuideDefine))]
    public class GuideDefineEditor : UnityEditor.Editor
    {
        #region 外部方法

        public override void OnInspectorGUI()
        {
            var define = (GuideDefine)target;
            if (GUILayout.Button("打开引导编辑器", GUILayout.Height(28))) GuideEditorWindow.Open(define);
            serializedObject.Update();
            using (new EditorGUI.DisabledScope(!GuideEditorModel.CanEdit(define)))
            {
                GuideEditorFields.DrawCondition(serializedObject.FindProperty("baseSkipAll"), "全局跳过条件", "未设置时不跳过");
                var steps = serializedObject.FindProperty("guideSteps");
                for (var i = 0; i < steps.arraySize; i++)
                {
                    var step = steps.GetArrayElementAtIndex(i);
                    var name = step.FindPropertyRelative("name").stringValue;
                    step.isExpanded = EditorGUILayout.Foldout(step.isExpanded, $"步骤 {i + 1} · {name}", true);
                    if (step.isExpanded) GuideEditorFields.DrawStep(step);
                }
            }
            serializedObject.ApplyModifiedProperties();
            using (new EditorGUI.DisabledScope(!GuideEditorModel.CanEdit(define)))
                if (GUILayout.Button("添加步骤")) GuideEditorModel.AddStep(define);
        }

        #endregion
    }
}
