// Generated by Ember Setup v{EMBED_VERSION} — 游戏页面注册表
// 由 Ember/Setup/初始化项目 从模板生成；后期可由 UIBinding 代码生成器自动维护。
using Ember.UI;

namespace {NAMESPACE}
{
    /// <summary>
    /// 游戏页面注册表 —— 所有 UI 页面的统一定义处。
    /// 每个页面声明一个 public static readonly EUIPageDef，
    /// 运行时通过 EUIManager.Instance.ShowMainPage(GamePages.XXX) 打开。
    /// </summary>
    public static class GamePages
    {
        // ============================================================
        // Background 层 —— 兜底背景（单例）
        // ============================================================
        public static readonly EUIPageDef EUIBackgroundPage = new("Packages/com.ember.ui/Runtime/Prefabs/EUIBackgroundPage.prefab", UILayer.Background, PageType.Background);

        // ============================================================
        // Normal 层 —— 全屏主页面
        // ============================================================
        // public static readonly EUIPageDef MainMenu = new("Assets/Game/UI/Runtime/Prefabs/MainMenu.prefab", UILayer.Normal, PageType.MainPage);

        // ============================================================
        // Popup 层 —— 弹窗
        // ============================================================
        // public static readonly EUIPageDef Settings = new("Assets/Game/UI/Runtime/Prefabs/Settings.prefab", UILayer.Popup, PageType.Popup);

        // ============================================================
        // TopMost 层 —— 顶层（引导、加载遮罩等）
        // ============================================================
        public static readonly EUIPageDef EUILoadingPage = new("Packages/com.ember.ui/Runtime/Prefabs/EUILoadingPage.prefab", UILayer.TopMost, PageType.TopMost);
    }
}
