// Generated by Ember Setup v{EMBED_VERSION} — Main 开屏动画基类
// 挂在 MainScene 的任意 GameObject 上：收到 MainSceneReady 后播放动画，
// 完成后广播 OpeningAnimationEnd（MainState 收到后进入 OnOpeningAnimationEnd）。
using Cysharp.Threading.Tasks;
using Ember.Core;
using UnityEngine;

namespace {NAMESPACE}
{
    public abstract class EUIMainAnimationStarter : MonoBehaviour
    {
        private void Awake()
        {
            EmberEventBus.Subscribe(EmberBroadcastEvent.MainSceneReady, OnMainSceneReady);
        }

        private void OnDestroy()
        {
            EmberEventBus.Unsubscribe(EmberBroadcastEvent.MainSceneReady, OnMainSceneReady);
        }

        private async void OnMainSceneReady()
        {
            // 开屏动画（子类实现），结束后框架自动广播 OpeningAnimationEnd
            await PlayOpeningAnimation();

            EmberEventBus.OnNext(EmberBroadcastEvent.OpeningAnimationEnd);
        }

        /// <summary>播放开屏动画。子类实现此方法，动画结束后返回。</summary>
        protected abstract UniTask PlayOpeningAnimation();
    }
}
