// Generated by Ember Setup v{EMBED_VERSION} — 游戏层启动器（可选）
// 框架默认 GameLauncher 已通过反射自动发现 GameInitState/GameMainState 等子类，
// 仅在需要注册自定义状态或扩展启动流程时创建本类。
using Ember.Core;

namespace {NAMESPACE}
{
    public class GameLauncher : Ember.Core.GameLauncher
    {
        protected override void ConfigureStateMachine(EmberStateMachine fsm)
        {
            base.ConfigureStateMachine(fsm);

            // TODO: 注册自定义状态
            // fsm.Register(new LoginState());   // 网游：Init → Login → Main
            // fsm.Register(new BattleState());  // 玩法：Main → Battle → Main
        }
    }
}
